### ISSUE TITLE
Create Amazon Business Acccount 

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#10]
Joe is currently using his personal Amazon account to order books and then claiming the expenses back. This isn't ideal for him, and it also means that order people CAN'T order books. Plus it's poor financial management.  

This issue is:
- [x] Create an amazon buisness account
- [ ] make sure that the password is secure and unshared.
- [x] check with trustees, 
- [x] do a test order
- [ ] evaluate if this should be permentent policy.

**Comment by joereddington** [comment]
###### 25/06/18 09:29: 
Let's go. I've got books to order. 

I'm using my eQuality Time address for now, this might change. 

###### 09:34: 
Okay, got this far.  I've also messaged a trustee to get their take. 
![screen shot 2018-06-25 at 09 34 08](https://user-images.githubusercontent.com/4369547/41839361-f66f5884-785a-11e8-8a0c-fada26ac2813.png)

**Comment by joereddington-public** [comment]
Amazon Verified us, I made a test order, and now I have to pay it by invoice.  That's the next action. Then we're talking to Trustees about switching entirely (and getting amazon prime on that account)

**Comment by joereddington-public** [comment]
The test order worked, I've put the invoice into amazon, and the trustees approved prime for it.  I did our first proper order on it today.  Will close this, but there is a follow up about adding other people to the account so they can make purchases.
