### ISSUE TITLE
Work with consultant to improve EQT policies

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#12]
From Comic Relief: 

> "So yes, as discussed we’ve given you an additional £3,500 to spend on consultancy to support the strengthening of your financial management and processes and your governance."

# Background
We want to have effective and up to date finantial management and governance.  As a secondary goals we also want to be able to demonstrate to funders and auditors that: 
* We are a safe pair of hands
* We have all our ducks in a row 
* We are 'sound'

Metaphors asside - we've been marked down by some funders recently on our govenance - Children in Need, Arts Council denied us funding on that basis and Comic Relief presumably don't give this money to people with all their ducks in a row.   So it would be extremely good to know what these funders are ideally looking for when they do their due dilligence. That's NOT to say we intend to completely capitulate, but if we know what they want they we can highlight the relevent parts. 

# What we want the consultant to do. 
Three phases: 
* Write a report with recommendations 
* Give us a few months to implement the recommendations 
* Come back, reassess and give us a testimonal we can put on the website that says "I, a proper clever person, think these guys are serious guys" 

As a bonus 'getting started' deliverable, we'd like the consultant to give us a model answer to a couple of questions we've had to funders - as discussed above, we can either work to make everything in the model answer true, or we can use is as a starting point. 

### The report 
We expect four sections in the report. The first two are should/musts for our organisation and they should make up the main proportion of the work. Items 3 and 4 are much smaller.  We recognise that all sections are somewhat subjective, particularly 3 and 4 and we would be happy to see the consultant 'get into character' for 3 and 4. 

1. We'd like a list of things that the charity should/must be doing at it's current size, 
1. We'd like a list of things that the charity should/must be doing  when it reaches, for the sake of the argument, a £250,000 turnover.  
2. We'd also like to consider [Thora Masoud](https://www.behindthename.com). Thora does due dilligence for a large UK funder and will assess us for a £400,000 grant sometime in the next five years. We'd like to know what she needs to see give us a clear bill of health.  We might NOT do any of them, but we want to know what they are. 
3. Lastly we'd like to consider [Argiñe Trafford](https://www.behindthename.com).  She is serious person in central government and she happens to be browsing our website because she is interested in one of our projects. We'd like to know what should be on our website in terms of finance and govenance to make Argiñe take us seriously. 
 
# How are we going to do this? 
* Weekly meetings, where we supply him with any information he requires. 
* Deadline date for report. 
* Share this issue with them, encourage them to use it. 

# Plan 
- [x] Recruit Consulant
   - [x] get recommendations from Comic Relief 
   - [x] get recommendations from MySociety (the organisation we'd like to grow up into)   
   -  [x] get term of reference from two consultances 
   -  [x] choose 
- [x] argree milestones and regular meeting time. 
- [x] Get report
- [ ] work on report in seperate issues 
- [ ] Get updated checks.

**Comment by joereddington-public** [comment]
I've emailed about this today.

**Comment by joereddington-public** [comment]
I've rewritten this based on What We Really Want.  Next action is to explain this to him, and see if we wants to play.

**Comment by joereddington** [comment]
One consultant asked for the Arts Council Feedback [export.pdf](https://github.com/eQualityTime/Public/files/2358066/export.pdf)

Interestingly we *met* the finance requirement on a previous application. 
[export (1).pdf](https://github.com/eQualityTime/Public/files/2358072/export.1.pdf)

**Comment by joereddington** [comment]
We've picked a consultant and we're going with them. They've asked for the following. 

> * All relevant financial management policies, procedures and templates including procurement
> * Delegated authority document (e.g. document which shows who can approve what)
> * Other key policies in place e.g. anti-fraud and corruption and whistleblowing

 All approved policies are in the policies section of http://equalitytime.co.uk/about-equality-time/ with the exception of [this general prodedure for approving expenses](https://docs.google.com/document/d/1yGuSQNRo4apLh4GUr2hU4tOYlSC4C0HdRENxqLjtGp4/edit?usp=sharing): 

>* Chart of Accounts - codes and structure

We do NOT have one of these. 

>* The 2018/19 approved organisational budget

We do NOT have one of these. 
>* A recent donor funding proposal and budget, plus recent rejected donor budgets and proposals e.g. Arts Council/Children in Need/Comic relief

Some useful links: 
* https://github.com/orgs/eQualityTime/projects/3 is the set of recent funding proposals and our notes on them. 
* http://equalitytime.co.uk/6143/2017/11/27/opening-up-our-bid-writing-process/ Drafts of a project application.  
* Arts Council Rejections are in the comment directly above this one.  The relevent application is http://equalitytime.co.uk/6217/2018/03/27/reviewers-wanted-for-battlecry/

> * Latest set of management accounts

There's a set in preperation, all other management accounts are in the 'Accounts' section of http://equalitytime.co.uk/about-equality-time/


>* A recent project financial report (for internal monitoring not for donor reporting)

None
>* Most recent donor reports - both financial and narrative

Only: http://equalitytime.co.uk/download/SupertitleAwards4All.pdf

>* Draft financial statements for 2017/18 if available for year ending 31 August 2018

I might need clarification on this one. 

>* Any recent audit reports (internal, external and/or donor)

eQuality Time hasn't been audited. 

>* Organogram

We do not have one. 

>* Latest Board meeting minutes where discussing the financial review/progress/forecasting/budget

All minutes are in the 'Minutes' section of http://equalitytime.co.uk/about-equality-time/

* Strategic plan and financing strategy
> We are due to aggree one I believe on Saturday.   (The last one ran out recently)

**Comment by joereddington** [comment]
Phone call with Rob, 

# List of Topics
 
> 2. model answers and ordering 

Aggreed to start with a 'model answer search' along the lines of 'couple of hours reading up, couple of hours writing' for either (or both) of the managument sections of the arts council or Children in need funding streams. 

> 3. Interviews

Trustees are availible to interview. JR to send email address.   

>  1. Instant reaction to state of docuemnts 

Done.

**Comment by joereddington** [comment]
We now have the report from Rob. It's here: 
[eQuality Time Financial Management and Financial Governance Review - final 21 Nov.pdf](https://github.com/eQualityTime/Public/files/2614994/eQuality.Time.Financial.Management.and.Financial.Governance.Review.-.final.21.Nov.pdf)

It's a little bruising, but it's also correct (and if your feedback isn't bruising...).  We'll be working on it in various forms over the next couple of months.

**Comment by joereddington** [comment]
The action points are sorted in this excel file: 
[Consultant Recommendations.xlsx](https://github.com/eQualityTime/Public/files/2615087/Consultant.Recommendations.xlsx)

**Comment by joereddington-public** [comment]
Reviewing document - we've ticked some actions off.  The new document is here: 
[Consultant.Recommendations.xlsx](https://github.com/eQualityTime/Public/files/2759505/Consultant.Recommendations.xlsx)

Next Action points are: 

- [ ] There   is a policy detailing who can authorise purchases of different types or   value.
>eQuality   Time should introduce formal delegated authority (within a delegated   authority document) that clarifies who has the authority for making financial   decisions, such as limits for committing, approving and authorising   expenditure, as well as signing other legal documents such as income   agreements. Proof of compliance with the delegated authority would be   required, for example if two people were required to authorise a specific   expenditure (eg on a purchase order).

- [ ] There is a go/no go process which consider both programmatic and financial elements   in decisions to proceed with funding for projects. 
- [ ] The   delegated authority document should include formal authorisation limits for   signing income agreements.
- [ ] Train staff 
- [ ] Monthly   bank reconciliations should be undertaken and reviewed by someone who did not   prepare them.

So... 

[eQuality Time - delegated Authority Policy.docx](https://github.com/eQualityTime/Public/files/2759609/eQuality.Time.-.delegated.Authority.Policy.docx)

Next actions: send to trustees and make this post a seperate issue.

**Comment by joereddington-public** [comment]
Next action: 

- open and change reserves policy. 
- Draft delegated authority document.

**Comment by joereddington-public** [comment]
[eQuality Time - delegated Authority Policy.docx](https://github.com/eQualityTime/Public/files/2759597/eQuality.Time.-.delegated.Authority.Policy.docx)

Next action is to send to trustees

**Comment by joereddington** [comment]
This has been replaced by https://github.com/eQualityTime/Public/issues/82
