### ISSUE TITLE
Contact prizes and see if we can sponsor a novel.

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#14]
The are prizes for novel writers, 

There are prizes for young writers 

There appear to be NO prizes for young novel writers. (we mean under 18 [this doesn't count](https://www.youngwriteraward.com/2017-shortlist-announced/)) 

We'd like there to be prizes for young novel writers. So we're going to ask some competitions what it would take to add a category, and if necessary we might consider sponsoring one.  

# Plan 

- [ ] Spend half an hour gathering a big list of children’s/YA writing prizes.  
- [ ] Phone the biggest (in terms of prestige, or in terms of having lots of categories) say, four, and find out what it would take. 

I'm assuming that a prize would amount to 'send the first chapter' and we'll shortlist 5, then send the next 30,000 words or similar...

**Comment by WhiteWaterLMB** [comment]
Although there are several single awards, there don't seem to be a great many multi-category things for writers, particularly the young. But I have found a few that might work.

[The Wicked Young Writer Awards](https://www.wickedyoungwriterawards.com/) (as in the musical) have age categories for shorter pieces, plus one for non-fiction, but nothing yet for longer pieces of fiction. I can't find a phone number for anybody involved with them anywhere, but there is a contact email address (info@wickedwritersawards.com), which I'm about to send something to.

There's [The Costa Book Awards](https://www.costa.co.uk/costa-book-awards/costa-book-awards/), which seems to be for all ages, but could perhaps benefit from adding a young writers award specifically. I've left their contact (Amanda Johnson, 07715 922 180) a voice mail and will give it another go later today.

[The Northern Writers Awards](http://northernwritersawards.com) has two categories for young people - one open to any kind of writing and one for development. I've spoken to their award manager Will, who isn't sure an additional category is the way to go, but is open to discussing a partnership on the current ones. His number is 0191 204 8850. He is about to go on holiday for two weeks, but has a colleague named Lizzie (who gets back from hers next week) and we can also speak to her about it. He's asked for an email to both will@ and lizzie@ newwritingnorth.com, which again, I'm about to send.

[The London Writers Awards](https://www.spreadtheword.org.uk/projects/london-writers-awards/) doesn't specifically have a young person's award yet, but could perhaps benefit from one. It provides masterclasses to its winners, so there is an educational link. Their overall aim is to increase the number of writers from under-represented communities being taken up by agents and publishers, which I'm sure would be a big help for the young as well. Would this be worth looking at?

There's also the [Scottish Book Trust Young Writers Awards](http://www.scottishbooktrust.com/writing/opportunities-for-writers/young-writers/young-writers-awards), if you're open to Scotland? Haven't contacted yet, as I wasn't sure. Again, it has an educational aspect.

[The National Young Writers Awards](https://www.explorelearning.co.uk/national-young-writers-awards/) is the most established set of awards, but it looked on their website like there are regional winners that get narrowed down to an overall winner, but the process was a little unclear. I have spoken to them (on 01483 447414) to confirm and indeed it doesn't have categories.

Would it be worth perhaps speaking to a publisher or book shop chain about creating a new award?

**Comment by joereddington** [comment]
I've sent some emails and badgered on Twitter - funnily enought one of our trustees does some work for the London Writers Awards.

**Comment by joereddington-public** [comment]
I'm closing this project - we didn't really find any takers (althought http://northernwritersawards.com/enter/ already has some catagories that a single young person could apply to with a novel) and the relevent funding will run out soon.  Will send around to see if the content is useful to anyone tho.
