### ISSUE TITLE
Joe to give his recommendation for 2019 strategy to trustees before AGM

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#16]
eQuality Time is coming to the end of it's financial year, and is coming to the end of the strategy that we wrote _last_ year.  So we need to look into creating a new one. 

# Plan 
- [x] review last strategy and see how well it worked. 
- [x] Write Joe's perspective and recommendations 
- [x] Send to trustees for review and brainstorming at AGM 
- [ ] Write up conclusions from AGM.

**Comment by joereddington-public** [comment]
I did some brainstorming on this: 



![screen shot 2018-07-13 at 15 27 34](https://user-images.githubusercontent.com/40637406/42696839-4ba48310-86b1-11e8-9bea-87734f3a3eee.png)

Next action is to write it up as a document.

**Comment by joereddington-public** [comment]
###### 19/07/18 14:59: 
I wrote this today and I've an outstanding action to send it to trustees for their review.

**Comment by joereddington-public** [comment]
(review) 
It's been sent, the next action is to confirm with trustees that I can blog it.

**Comment by joereddington** [comment]
> As we work broadly on academic cycles and the school term is coming to a close, I've been doing some brainstorming and thinking on where I think EQT should go in the future. I wanted to write down my current thoughts before I officially make recommendations to the trustees, so here that is. 
> 
> Joe
> 
> 
> What EQT should do in the next year.  By Joseph Reddington. 
> 
> It's been a good year. In the next 12 months we have a big Open Voice Factory project to make happen, a smaller Open Voice Factory project to do, and we expect a good amount of money to come in from supporting Keele's White Water Writers work. 
> 
> There are two questions: are we able to make good on our promises? If we are, what else can we do at the same time?
> 
> I believe we can make good on our promises, our work for Essex is in hand and should finish about the time that our comic relief work slips into higher gear. Also our support for Keele is needs only a needs small attention often. 
> 
> However, the Comic Relief bid is very large, and quite short: we have to spend quite a lot of money in a short time and spend it well.  I expect it to take up the most of our bandwidth. 
> 
> I believe it would be bad to take on another project while we are delivering comic relief because that gives an unacceptable risk of failure.
> 
> It is my belief that any spare resources that we have needs to be used to do the following: 
> 
> Continue writing bids to ensure EQT has work following on from the Comic Relief Project 
> Make EQT's organisation better - at the moment communication and money-moving both need to be fixed. 
> Help Keele scale up - they have more demand than supply right now if we can help them double their number of camps then that doubles the number of £600 licence payments that arrive. 
> 
> You'll notice I haven't included any of our own WWW camps.  THE SHINE grant subsidized them heavily for the last few years and now that has finished it has made them unprofitable to run. Even when they were subsidized  we were unable to book enough camps to fund the staff members. Keele avoid these problems by partnering with an organisation called High Horizons that introduces them to schools and pays their costs. I'm trying to arrange meetings with their London equivalents but so far have drawn a blank.

**Comment by joereddington** [comment]
It needs rewriting.

**Comment by joereddington** [comment]
Okay, we are discussing this at the meeting on wednesday and then should be released.

**Comment by joereddington** [comment]
Meeting was posponded, doing next time.

**Comment by joereddington** [comment]
This was approved at the right meeting - I need to move accross the meeting minutes and then blog this
