### ISSUE TITLE
Create Communication Board and recruit testers for Essex Challenge Prize 

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#19]
This is part of the [Essex Challenge Prize Project](https://github.com/eQualityTime/TheOpenVoiceFactory/wiki/Essex-Challenge-Prize), please see that wiki page for more information.  

# Plan
- [x] alert contacts that we are looking for a dementia researcher for some freelancer work (to rewrite the current CK20 Communication board to be focused on Dementia) 
- [x] interview  (one down)  
- [x] Arrange User testing
   -  [x] Shortlist care homes who might be interested. 
   -  [x] Call the domain experts about it.   
- [x] select freelancer and set deliverables
- [x] Find care homes 
- [x] Get printouts to review 
- [x] review printouts 
- [x] make packages
- [x] send. 

# Notes 
This issue was originally the only issue for the project, so contains some additional text in the comments.

**Comment by joereddington** [comment]
Gone back and forth on this a few times - the next action is actually to go over Challenge demenita doucments in detail...

**Comment by joereddington-public** [comment]
Update. 

I interviewed someone for the production of the special communication board. They were very good and I've offered them a job. Hopefully they'll produce a first draft shortly.   

Next issue to deal with is the user testing. And the first part of that, is to go properly through the materials from the Funder again - it includes a bunch of resources that we should be using.

**Comment by joereddington-public** [comment]
-  freelancer has accepted and we've arranged meeting ✅ 
- I also did a brainstorm on the concept - I know how to present it now ✅ 
- I also know how I want to do user testing ✅ 
- Contacted a care worker to find out what would be a nice 'care' package for people working in a care home ✅ 

We are, in this project, all about low-cost, low-effort, and low-risk.  We accept that there might be relatively low benefits, but if every board we make stops a person bursting into tears every two weeks for £5.99, than that's a win for me. 

So next actions. 
-  Monitor freelancer
- Go through the list of contacts that Challenge Dementia sent us.

**Comment by joereddington** [comment]
@WhiteWaterLMB - can you take half an hour and find a list of (ideally demtia focused) care homes in essex?  There is presumably one somewhere (and if there isn't - I might FOI one, it must exist)

**Comment by WhiteWaterLMB** [comment]
No problem. I’m sure there are a few. One of the homes nearest to me is a dementia home and is part of a chain. The others have to be somewhere.

**Comment by joereddington-public** [comment]
Just had a meeting with our Researcher, she's done some solid background research and is read to produce the first draft - with a expected deadline of Sunday.  After that, I'm going to send it to some people for design input, with a *hope* that we have a version ready to be printed by end of July.  

In the mean time I've send the other people in the prize: the medical device info and the ethics info.

**Comment by joereddington** [comment]
On call with Aideen,  

Draft board is done and [is here](https://www.dropbox.com/s/wpqb9krzgs7010a/Dementia%20board.pptx?dl=0).  Next actions 

- are to fill in the missing icons (mostly from http://www.arasaac.org/index.php), which anyone can do,
- Aideen to write up the design decisions in a short exec summary 
- The care homes to be chased.

**Comment by Lewiscowles1986** [comment]
Don't know if this will help, but here are a list from my local area in Essex

* https://www.carehome.co.uk/care_search_results.cfm/searchunitary/Basildon/searchchtype/alzheimers-and-dementia

**Comment by joereddington-public** [comment]
Okay, lets have an update. 

I've got two care homes who are interested, and so I need to print them a poster and make up a package.  

First I've got to add in missing icons.

**Comment by joereddington** [comment]
Email our researcher with what turned out to be a fair summary of my thinking: 


> 
> I failed to make a note about when you are coming back.  Let me know when you are. I want to talk to you about the boards.  
> 
> The point I want to make is this: some of the icons are hard to relate to the words (I'm thinking of 'stay') which potentially reduces their usefulness.  Is it possible that we would get more value if we used slightly less useful words that have more accessible icons? 
> 
> Also - I added a bunch of symbols for the obvious ones so there is a new version: https://www.dropbox.com/s/z6n1rwj6cnwxp47/Dementia%20board%20v0.2.pptx?dl=0
> 
> Useful note - we've now had confirmation from some care homes who wish to trial it so we can send this out pretty soon. 
> 
> J

**Comment by joereddington-public** [comment]
Update: there is a new complete version of the board in Dropbox 
Next action: send board to printers so you and the researcher can make final adjustments 

# Plan 
* get final printouts 
* Prepare care packages 
* Send to care homes 
* Do follow up email 
* Calendar event for response. 

In terms of timing. 
I'd like some initial results by the 5th September 
That means they should be up in care homes by the 20th August. 
Posted by the 16th. 
At printer by the 13th.
Great because I'm meeting the researcher then. 
Initial version posted by today...

**Comment by joereddington** [comment]
###### 09/08/18 11:27 to 12:08
Started work. Our researcher has added lots of content to [our dropbox directory](https://www.dropbox.com/sh/fgv2az9w7r6nnzl/AAAclpuZd9DSyTpzDfmQwKyVa?dl=0), including a fully drafted board. I've ordered her a copy to look at.

**Comment by joereddington** [comment]
###### 09/08/18 12:13: 
Turns out I ordered it before remembering that I was supposed to replace two of the symbols. Starting again.

###### 12:22: 
Done.  For those keeping score - I'd have saved us £20 if I'd have done it yesterday :(

**Comment by joereddington-public** [comment]
I've reviewed the printouts. The next action is to: 

* Buy some postal boxes that can fit an a2 poster tube and some a3 card in it. 
* Buy sweets to go in the postal post 
* send corrected poster and board to to printers (3 copies of each) 
* Write up the instructuions as a word document. 


Instructions 

> Hello! 
> 
> Thanks for helping us test our promoting boards. 
> 
> In this package you will find: 
> 
> * An A2 wall poster in two parts. 
> * Some bluetack to put the poster on the wall 
> * Some handcream (we asked care home staff what they could do with and this was their answer) 
> * An smaller communication board in case that comes in handy. 
> * Chocolates as an early thank you. 
> 
> Please put the poster on the wall in a common area, we're hoping it will be useful for some of your clients who have trouble finding the right word at the right time.  We'll call up in a couple of weeks to see if you noticed any benefit - we don't expect them to change anyone's life, but if one less resident bursts gets angrily frustrated a week then we'll be happy with the result. 
> 
> Yours 
> 
> Dr Joseph Reddington 
> eQuality Time

**Comment by joereddington-public** [comment]
###### 28/08/18 11:59,
The boxes are packed! 

![dsc_6643](https://user-images.githubusercontent.com/40637406/44719049-0176c500-aaba-11e8-9c7f-a33009a02779.JPG)

The next action is to address them and take them to the post office.  Then we have a finalist meeting to go to.
