### ISSUE TITLE
Submit Bid to the National Lottery

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#2]
# Reaching Communities England
The intented target is Supertitle

## Resources
* [main site](https://www.biglotteryfund.org.uk/funding/programmes/reaching-communities-england#section-1) 

# Deadline 
None
 
# Plan 
#### Plan (updates and changes a lot) 
- [x] Phone call to see if we are eligable 
- [x] create the folder in Dropbox
- [x] Submit idea
- [x] Wait
- [x] have review call 
- [x] prepare finantial documents 
- [ ] wait again.

**Comment by joereddington** [comment]
###### 10/05/18 11:33: 
Let's have a go at this. Next action was
- [x] create the folder in Dropbox
Done.
- [ ] Create a word document with all the application form questions in.
Going to the site...

###### 11:38: 
Actually. The first phrase is literally a text box (the other four steps are organisation name and so on... 
![screen shot 2018-05-10 at 11 35 46](https://user-images.githubusercontent.com/4369547/39865991-bb4ff34a-5446-11e8-8fb2-7ffc5a162141.png)


'lnn

###### 11:40: 
Okay, let's put something together
* We're seeking funding Towards salary costs of a Project Manager and Supertitle facilitators at a project in 50 schools in London to improve English as an Additional Language (EAL) students’ confidence, locus of control and self-esteem.

#The problem
The BBC iPlayer and other TV on demand services give out subtitling in English. However, almost 1 in ten UK households have a member that doesn’t have English language, (“In 91% of households, everyone speaks English. In 4% no one speaks English as main language.” http://www.theguardian.com/uk/blog/2012/dec/11/census-data-released-live-coverage) with other languages including Polish, Punjabi and Urdu. http://www.independent.co.uk/news/uk/home-news/polish-is-second-most-spoken-language-in-england-as-census-reveals-140000-residents-cannot-speak-english-at-all-8472447.html  In such households UK media is generally not watched in order to avoid (further) isolating members of the household, even if, for example schoolchildren in the households have a desire (or even, given the politics of the playground, a social need ) to consume traditional UK media.  This state of affairs perpetuates at the expense of such households, with non-english speaking members continuing to be isolated, and with barriers being placed between the English speaking members and their peers.  

Indeed, the UK education system is not fit for purpose in our modern day, diverse society. “The proportion of students recorded as EAL varies widely across the English regions, ranging from around 6% in the South West and North East to 43% in Outer London and 56% in Inner London” (https://v1.educationendowmentfoundation.org.uk/uploads/pdf/EAL_and_educational_achievement2.pdf) . However many schools struggle to find the staff time, resources, or initiatives to help these students reach their full potential. This results in adolescents from migrant backgrounds being routinely placed in classes for low ability pupils because bilingualism is still wrongly associated with special education needs. These children do not get the quality education they deserve, which affects their self-esteem and confidence 
As a result, many bilingual secondary children identify themselves as monolingual. Their experience is that their home languages are of little value in the education system  (http://www.ioe.ac.uk/56528.html).

#Our Change
We're going to set up Supertitle clubs in 50 schools in London (we have sucessfully piloted with 8). 
Supertitle sessions are led by a facilitator and typically involve 10 EAL students of the same target language. The session takes place in the school’s computer room. Students are offered a selection of BBC TV programmes  and collectively choose one to develop. They are provided with the English language subtitles for the programme and then, using our bespoke software, organise themselves to produce translated text. Once completed, the subtitles are freely available online for any member of the target language community to watch with the programme.  Students typically screen the programme for family members at home, and at the end of the term schools provide a group screening of selected programs. 

###### 11:47: 
Okay, that description really doesn't capture what we do, but it does give an outline of the problem.  I'm happy with it. Submiting.   

Next action: we wait.

**Comment by joereddington** [comment]
(from notes) 

###### 13/06/18 08:08 to 08:34:
Our contact at the lottery has come back to ask for our budget and project length. I'm a little unsure about how much is possible here, so I'm have prepared three potential plan for her.  Here's the email as writen and I've attached the spreadsheet: 

>You asked about budgets and timescales: we've actually got three potential scinarios - covering everything from an extended pilot, to scaling the project to a self-funding level. I was unsure which to send you, so I've attached the figures for three.  They are: 
>
> Option 1: extended pilot: 
> This is running the intervention in 50 schools over 12 months, using one facilitator, building a repository of programs, and gathering data. 
> 
> Option 2: broad rollout: 
> This is running the intervention in 100 schools over 18 months using two facilitators( one with fewer working hours). 
> 
> Option 3: scaling up: 
> Running the intervention in 150 schools over two years, allowing us to gather and publish performance data and charging schools for the intervention. 
> 
> I suspect it's easy for you if we pick one, but I was hoping to get your take on which would fit the best with the fund priorities. 
>  
[Three budgets for the national lottery.xlsx](https://github.com/eQualityTime/Public/files/2101625/Three.budgets.for.the.national.lottery.xlsx)

**Comment by joereddington-public** [comment]
(review) 
Last time we spoke to the National Lottery Assessor she was pitching it to her team. 

Next action: we should follow up and find out what happened.

**Comment by joereddington-public** [comment]
Before I could follow up, I was contacted by our handler's boss - our handler has left comic relief and she is taking the bid over. I've send her over a bunch of material. I'm a little worried that she's less familiar with the project, but we'll see.

**Comment by joereddington-public** [comment]
Turned down.

Wait - it's about being guided through a process - so we should say "Okay, what's the best evidence we can give you that we can be in that number of schools?

**Comment by joereddington-public** [comment]
I asked for feedback - haven't had any yet.
