### ISSUE TITLE
Apply to Aldgate & Allhallows Foundation

### ISSUE THREAD

**Issue by joereddington-public** [eQualityTime/Public#22]
# Resources 
* [Website](https://aldgateallhallows.org.uk/grants/grants-for-schools-organisations/) 

# Plan 
- [x] call up with questions 
- [x] decide which project (white water writers)

**Comment by joereddington** [comment]
I had a phone call with the staff. 

The fund is very full. The September deadline is very full, and the April one is filling up on a first-come basis.  We should put something in around October 2018 for April 209. 

We've been sent a template, it should be two pages. We should focus on: 

- Why these kids have been selected
- What are the outcomes and what evidence we have 
- Who is the main beneficiary.

**Comment by joereddington-public** [comment]
###### 30/07/18 16:13: 
The next action is to start filling out to form.

**Comment by joereddington** [comment]
[C. AAF Organisation Application Form.docx](https://github.com/eQualityTime/Public/files/2249256/C.AAF.Organisation.Application.Form.docx)

**Comment by joereddington** [comment]
They don't like mother tonuge teaching so it looks like it would be WWW?
