### ISSUE TITLE
Send start up form to comic relief by 1st August

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#23]
One of the conditions of accepting the comic relief funding was that we fill out some forms at the start. 

# Resource
* [site](https://www.comicrelief.com/funding/managing-your-funding/documents)
* [Guidance Notes](https://www.comicrelief.com/sites/default/files/downloads/cr_grants_managing_Guidance-for-completing-start-up-form-Level-1.pdf)

**Comment by joereddington-public** [comment]
###### 19/07/18 14:58: 
I've filled in some very simple answer, but most of the documents are on the other account.  
[cr_grants_managing_Level-1-Start-up-form.docx](https://github.com/eQualityTime/Public/files/2210203/cr_grants_managing_Level-1-Start-up-form.docx)

Next action is to copy/paste from the application forms and then tidy up.

**Comment by joereddington-public** [comment]
###### 30/07/18 13:31: 
Working on this now. 

Questions:

* 3.1 Who and how many are benefitting directly from your project   overall

Otherwise the form is finished at: 
[cr_grants_managing_Level-1-Start-up-form v0.2.docx](https://github.com/eQualityTime/Public/files/2241133/cr_grants_managing_Level-1-Start-up-form.v0.2.docx)

###### 13:43: 
Done.

**Comment by joereddington-public** [comment]
###### 30/07/18 15:32: 
(reviewing) 
Next action is to send the form: 

> Hi X, 
> 
> Completed form here: [cr_grants_managing_Level-1-Start-up-form v0.2.docx](https://github.com/eQualityTime/Public/files/2241133/cr_grants_managing_Level-1-Start-up-form.v0.2.docx).  One small point - were it said "Who and how many are benefitting directly from your project overall" I've taken it as "Who and how many will benef directly from your project".  Hope that makes sense and speak soon. 
> 
> Joe

**Comment by joereddington-public** [comment]
Sent.
