### ISSUE TITLE
Update policies

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#27]
We've got a new document management policy. 
[Document Management Policy v0-2.docx](https://github.com/eQualityTime/Public/files/2211020/Document.Management.Policy.v0-2.docx)

All of our policies in [this folder](https://www.dropbox.com/sh/ec5sl8wfulvxjhh/AACm8b1AnBFxD8lP7SK6dzzpa?dl=0) are now 'controlled documents'  which means thy all need to have the bit at the top that says who wrote them (me), who (approved them) the trustees, and the version (which will be 1.0 for all of these because they've been approved and haven't been touched since.

**Comment by WhiteWaterLMB** [comment]
Have edited and uploaded [here](https://www.dropbox.com/sh/m18x8c9jj93eobj/AAA66pAssGTEh2AvlhLgx6jTa?dl=0), as was no upload option on this folder.
