### ISSUE TITLE
Create financial plan for comic relief

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#30]
We have a budget from Comic Relief. You can read about our work with CR in this [wiki page](https://github.com/eQualityTime/TheOpenVoiceFactory/wiki/Comic-Relief-Tech-for-Good-Program) 

We also have nine months to spend it and any money left over will be returned.  So we should try and make sure we do.  

# Context 
Comic Relief is part funding the overall project and the other amounts don't have to be returned as quickly so we should know which parts can be delayed if we need to. 

# Plan 
- [x] make sure that project manager role is included in the COO role. 
      - [x] Check this arrangement is okay with CAST
      - [x] inform trustees 
      - [ ] produce a document detailing the change. 
- [x] Make the budget public 
- [x] Seperate the budget into 'monthley outgoings' (like project manager') and 'project outgoings' like code bounties and core costs).  Make that spreadsheet availible (assume that we have nine months since the project start to spend the money.
- [ ] brainstorm on projects for the project line items. (we know why we need them, we want to check if we're doing them the best way)  
- [ ] look at the original budget, work out why you have transport in there twice. 
- [ ] find out what level of accounts CR want - presume core costs needs NO evidence. 
- [ ] Confirm the spending details with the CR and CAST people.  
- [ ] Create issues for the project outgoings (including publicity)  
- [ ] Work out from the budget how much time we shall have for software engineers at the current rate. 

# Overall budget 

| Title | amount | 
| --- | --- | 
| Software Engineer 0.5FTE                                                       | £6,875.00  |
| Project Manager 0.5FTE                                                         | £21,091.00 |
| Core costs - including Office costs and administration                         | £3,500.00  |
| Accountants fees                                                               | £700.00    |
| Transport                                                                      | £400.00    |
| Publicity                                                                      | £2,937.00  |
| Transport                                                                      | £400.00    |
| Server Costs                                                                   | £150.00    |
| Code bounties for open APIs used                                               | £3,000.00  |
| Interface Designer                                                             | £3,000.00  |
| Focus Group review                                                             | £2,000.00  |
| --- | --- | 
| Total                                                                          | £44,053.00 |

## Line items that are monthly or gradually used up. 
| Title | amount | 
| --- | --- | 
| Software Engineer 0.5FTE                                                       | £6,875.00  |
| Project Manager 0.5FTE                                                         | £21,091.00 |
| Transport                                                                      | £400.00    |
| Server Costs                                                                   | £150.00    |

## Line items that are projects or accounted for. 

| Title | amount | Issue |
| --- | --- | --- |
| Core costs - including Office costs and administration                         | £3,500.00  | Uneeded |
| Accountants fees                                                               | £700.00    | #40 | 
| Publicity                                                                      | £2,937.00  |     | 
| Code bounties for open APIs used                                               | £3,000.00  |    |
| Interface Designer                                                             | £3,000.00  |    | 
| Focus Group review                                                             | £2,000.00  |    |

**Comment by joereddington-public** [comment]
Next action is to make the budget public. 
I've been chasing about the payment will ask if this means we have less time to spend it.

**Comment by joereddington-public** [comment]
###### 28/08/18 11:07,
The money is now in our account, I've also added the budget to the Wiki page. This is good. 

One action to do is to ask comic relief the question: "Since you only paid us at the end of August, do we only have 7 months to spend the money, or does our 9 start now?", but nicer than that.

**Comment by joereddington-public** [comment]
It turns out that our money needs to be spent by April.  So we should get on that. 

Next actions: 
- [ ] work out what we have spent so far. Broken down by month 
- [ ] work out what we expect to spend

**Comment by joereddington** [comment]
This has moved into the general Quickbooks updating.
