### ISSUE TITLE
Publish Open Voice Factory risk assessment

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#31]
It needs a risk assessment (I swear I did one) and it should be public.  

# Resources 
* The current state of the risk assessment is [here](https://github.com/eQualityTime/Public/issues/7)

# Plan 
- [x] find template 
- [x] draft risks 
- [ ] send to GM for feedback
- [ ] Make public for feedback (with named people) 
- [ ] Add to file.

**Comment by joereddington-public** [comment]
Done http://equalitytime.co.uk/6299/2018/08/29/writing-a-risk-assessment-for-software/
