### ISSUE TITLE
Medical Device Policies have Trustee approval 

### ISSUE THREAD

**Issue by joereddington-public** [eQualityTime/Public#37]
In #7 Greg and Joe developed some policies that are needed for the Open Voice Factory to be registered as a medical device. They all. 

* [Development.policy.v0-6.docx](https://github.com/eQualityTime/Public/files/2231932/Development.policy.v0-6.docx)
* [Risk.Policy v0-3.docx](https://github.com/eQualityTime/Public/files/2400893/Risk.Policy.v0-3.docx)
and 
[OVF.risk_.assessment.v0.3.docx](https://github.com/eQualityTime/Public/files/2357650/OVF.risk_.assessment.v0.3.docx)

* [Document Management Policy v0-2.docx](https://github.com/eQualityTime/Public/files/2155096/Document.Management.Policy.v0-2.docx). 
(https://github.com/eQualityTime/Public/files/2185032/Continuous.Improvement.Policy.v0-3.docx)
*  [PMS v0.1.policy.docx](https://github.com/eQualityTime/Public/files/2198381/PMS.v0.1.policy.docx)
* [Continuous.Improvement.Policy.v0-3.docx](https://github.com/eQualityTime/Public/files/2366751/Continuous.Improvement.Policy.v0-3.docx)

This issue is to get a majority approval from the four trustees. We've had confirmations from TJR, and both FB and SJ have 'approved if CW does' (because CW is a software engineer). 

# Plan 
- [ ] Contact CW and ask if there are any changes they would like to the documents.

**Comment by joereddington-public** [comment]
They have been sent to trustees, the next action is to badger the trustees.

**Comment by blaise17** [comment]
The continuous improvement policy isn't linked

**Comment by joereddington** [comment]
Fixed.

**Comment by joereddington-public** [comment]
Risk policy has been updated - see #47 for details.
