### ISSUE TITLE
Properly Document G-suite accounts

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#4]
We've started using G-Suite so that writers on the White Water Writers project can have many different accounts. 

The initial trial has been sucessful, but there is more to do. 

# Objectives
* Investigate if we qualify for low-cost accounts as described [here](https://webapps.stackexchange.com/a/116592/10707) 
* Create other administrator accounts so that team leaders can control 
* Fix the odd bug with passwords (bulk uploaded passwords aren't accepted, they have to be reset on the site) 
* Create relevent documentation
* Regular calendar event so that we can delete unused accounts - we pay per account per month.

**Comment by joereddington** [comment]
###### 14/05/18 11:14: 
On the topic of low-cost accounts - we've applied for G-suite for non-profites, and will be emailed. 
![screen shot 2018-05-14 at 11 13 50](https://user-images.githubusercontent.com/4369547/39991601-fdc9583c-5767-11e8-854c-3e376f805a11.png)

**Comment by joereddington** [comment]
I've asked the SE question here: https://superuser.com/questions/1323331/g-suite-password-requires-resetting

**Comment by joereddington** [comment]
It was the wrong place: I've re-asked it here: https://webapps.stackexchange.com/q/117250/10707

**Comment by joereddington** [comment]
###### 14/06/18 10:18 to 10:47: 
Rang Google Support today, but didn't get very far. I've now created an entirely new cohort, which I will try to log in with 24-hours after I get the confirmation email. 
![screen shot 2018-06-14 at 10 43 40](https://user-images.githubusercontent.com/4369547/41404928-648d5aee-6fc0-11e8-8ed5-2577ce627ee5.png)

**Comment by joereddington-public** [comment]
(review) 

The accounts are now working!   Here are the next actions: 

- [ ] delete and recreated the green1..10 accounts. 
- [ ] Put the bulk account  creation tool in this issue. 
- [ ] let all staff know that these are the correct accounts to use.
