### ISSUE TITLE
Do user testing for Essex Challenge Prize

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#41]
For the [essex challenge prize](https://github.com/eQualityTime/TheOpenVoiceFactory/wiki/Essex-Challenge-Prize) we produced an intervention and we tested it in some care homes. 

We need to be quite careful about how to treat this issue because it shouldn't be entirely public.  However - getting the information from the carehomes can be.

**Comment by joereddington-public** [comment]
Next action is to email the remaining care home and get some data out of them.
