### ISSUE TITLE
Submit buisness case for Challenge dementia by noon 1st November

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#42]
As part of the [Essex Challenge Prize](https://github.com/eQualityTime/TheOpenVoiceFactory/wiki/Essex-Challenge-Prize) we need to write a buisness case.  

Final deadline is (noon) 1st November 

"To bring your buisness case to live, you are asked to produce a short film" 

# Check List
- [x] Find the template 
- [x] Draft 
- [x] Get feedback. 
- [ ] Make sure you have attributed: https://www.opensymbols.org/symbols/noun-project/dentures?id=84251 and https://www.opensymbols.org/symbols/sclera/monopoly?id=16131

**Comment by joereddington-public** [comment]
Next action is to upload the buisness plan here.

**Comment by joereddington** [comment]
[Project Whatchamacallit business case.docx](https://github.com/eQualityTime/Public/files/2615155/Project.Whatchamacallit.business.case.docx)
