### ISSUE TITLE
Prison cable networks

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#44]
We need to be able to run an secondary IT network within a prison, entirely without power or cabling and we need to be able to persuade the prison to let us use it. 

We're looking at a plan that lets us have a battery powered router, a set of tablets, and 'host' computer that is running some sort of collorative writing program.  

So the plan is: 

- [x] buy router
- [x] Test router works fine offline (and break the 3G connection cabablities) 
- [x] check tablet accessing of host servers (websites, and sharable text) 
- [ ] Check you can use etherpad on your laptop 
- [ ] buy a bunch of tablets 
- [ ] check multiple tablet accessing 
- [ ] Write 'saving'/compiling code on host.

**Comment by joereddington-public** [comment]
Had a text message exchange about this today. Ideal if something is ready by the week of the 7th November.

**Comment by joereddington** [comment]
There's a good article on the chonical about installing on osx

**Comment by joereddington** [comment]
Conditions have changed a little and we are closing this project.
