### ISSUE TITLE
Review this form for Comic Relief.

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#45]

**Comment by joereddington** [comment]
[eQuality Time AB comments.docx](https://github.com/eQualityTime/Public/files/2378808/eQuality.Time.AB.comments.docx)

**Comment by joereddington-public** [comment]
Made some changes. Can be sent. 

Hi Martha, 

Changes made - I've also left track changes on so it's a little more obvious. Let me know if you would like another itteration. 

J 
[eQuality.Time.AB.comments.docx](https://github.com/eQualityTime/Public/files/2387974/eQuality.Time.AB.comments.docx)
