### ISSUE TITLE
Create video for challenge dementia by noon 1st november.

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#46]
For the [Essex Challenge Prize](https://github.com/eQualityTime/TheOpenVoiceFactory/wiki/Essex-Challenge-Prize) we need to create video.  Maximum length is 3 minutes and it should be sharable with partners and people living with dementia.

# Thoughts 
* Unethical to use people with Dementia directly. And a serious imposition for care homes to film for us.  So sensible to mock up our own with actors. 
* Would be better to have slides/storyboard before getting filming done. 
* Needs a name... 
* "Please ensure the film includes your name and your project name at the start."

# Plan 
- [x]  Storyboard
- [ ] Create slides 
- [ ]  Recruit actors (clearly likely to me Joe's mum and dad) 
- [ ] write 3 minute (250 word) script 
- [ ]  do draft video with slides and mocked up footage
- [ ] Send draft video to actors 
- [ ] Edit final set together. 

# Storyboard look like. 
Well... let's do a Pizar version.... 

* Once upon a time there lived a man in a care home 
* Every day he struggled with aspasia caused by dementia. 
* One day a poster arrived 
* Because it was always in view, he saw it when he was struggling to find words 
* Because of that he could use to to find the word he wanted to communicate better with staff. 
* Because of that he was less frustrated
* Until finally he started using his own version and writing his one words into it. 
* Short pitch "This is a, it requires NO technology, NO special training, you put it on the wall and it helps a little bit. it doesn't change anybodies lives dramatical.y But it does make everything a tiny bit easier.

**Comment by joereddington-public** [comment]
Next action is to do a rought iMovie version of that storyboard with some toys used as stand ins.

**Comment by joereddington-public** [comment]
This was done. The video was a little rough around the edges, I'm NOT going to share the final one.
