### ISSUE TITLE
Update the Risk Policy to reflect the requirements of ISO 14971

### ISSUE THREAD

**Issue by greg-westnine** [eQualityTime/Public#47]
@joereddington The risk policy is updated here:
[Risk.Policy v0-2.docx](https://github.com/eQualityTime/Public/files/2389171/Risk.Policy.v0-2.docx)

This is informed by [this](https://www.greenlight.guru/hubfs/Sales_Material/gg_guide_to_risk_management.pdf).

Next I will create a risk management plan for The Open Voice Factory.

**Comment by greg-westnine** [comment]
I've done some further updates to the policy:
[Risk.Policy v0-3.docx](https://github.com/eQualityTime/Public/files/2400893/Risk.Policy.v0-3.docx)

**Comment by joereddington-public** [comment]
I think I'm happy with this - I've updated #37 so that this is the most recent version.  Shall we close this issue?

**Comment by greg-westnine** [comment]
We can close this issue, but I think it is likely that further updates will be required when we review the policy against an actual copy of ISO14971.
