### ISSUE TITLE
There are 10 public eQuality Time projects 

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#5]
Our public projects are better maintained, and get more progress than the projects we list internally. I'd like there to be more of them. 

Some of these projects will be new projects that default to being public and some will be current ones that move accross. 

# Plan 
- [x] Go through next actions to find projects that should be mapped. 
- [ ] Rewrite the highest priority projects in 'home' issues to be public.

**Comment by joereddington** [comment]
###### 14/06/18 10:47:
Started mapping this project

###### 10:59: 
Mapped the Accountants project. 

###### 11:05: 
Mapped a Funding project that I was excited about it, only to discover that the deadline was April.  Update your websites people! 

###### 11:10: 
Moved over the project about Medical Devices.

###### 11:12: 
I've looked at other projects to move over. The next action is to properly clean up the main projects list.

**Comment by joereddington** [comment]
(review) there are now 6

**Comment by joereddington** [comment]
###### 25/06/18 09:35: 
(Review) there are 8 (including this one, which probably shouldn't count), but we're adding the comic relief one and I'm increasingly leaning into this.

**Comment by joereddington-public** [comment]
There are now 10! Whoop! 

<img width="985" alt="screen shot 2018-07-02 at 09 13 40" src="https://user-images.githubusercontent.com/40637406/42152532-5446be48-7dd8-11e8-96ee-27b43c0501c0.png">
