### ISSUE TITLE
Apply for Nesta Collective Inteligence grant by 9th November

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#51]
# Resources 
* [Main site](https://www.nesta.org.uk/project/collective-intelligence-grants/)
* [Application form](https://www.surveygizmo.com/s3/4555565/Collective-Intelligence-Grants-Application-Stage-1-version-A) 

# Plan 
- [x] Draft answers to application form 
- [ ] Go throught the online docs again looking for anything you have missed.  
- [ ] Put application form throught simplewriter 
- [ ] get application form checked over
- [ ] submit.  
- [ ] Blog it.  

Putting it thought SimpleWriter: 

# Application form 

## Proposal name
Fig Leaf 

## Proposal summary
_100 words_ MAYBE _150 words_ 
The second-hardest job in research is running focus groups: 90 minutes to build trust and get actionable insight from seven people without leading them.  The hardest job in research is to write up a focus group in an unbiased, interesting, and actionable way.

We’re going to make the deepest, most compelling dives into serious issues you’ve ever seen because we’re going to take 10 people with lived experience of an issue, put them in a room for a week and get them to write a story.    

If the story is judged to be a more compelling, true, and deep picture of what it is to live with these issues, then we will have shown that collective intelligence can give a more effective, cost-effecive way of attacking social problems. 

## Please explain what you are wanting to test/learn through your experiment(s)? And what outcome measure(s) do you envisage using to answer this? 
_150 words_

We think short and intense collective intelligence approaches can give more insight into social problems than traditional methods. In particular we think that we can do this by having people build narratives around issues they have lived experience of.  We think this allows us to get better results, and get them both faster and cheaper than traditional forms of social research. 

Our outcome measure is:  what proportion of users of a 'normally run' focus group feel that extracts from our novel reflect their lived experience better than their own answers in the focus group?  

## How do you plan to carry out your experiment? 
_250 words_

We’ll test this by creating three novels focused on dementia, eating disorders, and bipolar disorder and then conducting an analysis of the work and comparing the results with the existing body of social research on those topics.  

We'll create these novels using the TooManyCooks framework. TooManyCooks is an established collective inteligence approach for novel writing in short intense bursts.  It's school imprint, White Water Writers, has produced over 100 novels under the pen name T. M. Cooks.  TooManyCooks sets out a method for decentralised roles with clear responsibility and motivates the partipants with the knowledge that their work will be availible to buy on Amazon at the end of the week. It's so far been successful in prisons, schools, universities, threatres and hospices and this experiment is the first to focus primarilly on lived experience. 

## Please outline how this will help create actionable insights for practitioners and have wider applicability? 
_150 words_
If our experiment is a success, it will support the idea that collective intelligence methods like TooManyCooks, which prioritise motivation, artifact creation and clear decentralised roles and responsibilities, are effective at tackling social research in populations that have proved resistent to standard techniques.  It will searve as a blueprint for user-lead communcation of issus for a wide range of potential applications all the way form Wikipedia's problems with onboarding new editors to enabling effective citizen journalism. 

From an academic perspective, the collective intelligence field is dominated by projects that have thousadns of users making tiny edits, rather than small teams working intensely - our experiment will help fill out that imbalance.  

## Please describe if your experiment is part of a larger practical project or research programme  _150 words_ 

It is.  The TooManyCooks frame work is being used in schools all over the country as part of our work using collective intelligence for education.  Over 1000 students have used writing a novel with us as a catalyst to improve their creative writing and teamwork skills. 

We've also been evaluating it's potential for commerical fiction, which is an ongoing interest because that would help fund our work in schools. 

This work fits well within out current research adenda, several members of the project team are academics and have been looking critically into the process, and the outputs from the process. 

## Do you anticipate requiring support from Nesta to help with the design and/or delivery of your experiment? *
We've worked with Nesta before, and been hudgely grateful for the sensible feedback, ideas, new approaches, and good working enviroment we received, but we didn't know we needed any of that when we started.  

In this case, we do know what we need.  We've been building this collective intelligence project for a long time, but we didn't know that it was collective intelligence - we need to be working closely with people who know the field and who can help orident us with regard to other works.  This is everything from simply knowing what the slang in the area is, to being put in touch with groups that might like to see what we do.  
 

## Please tell us briefly about your team and its experience relevant to your proposal
_150 words_
_to copy and paste from the website_

**Comment by joereddington-public** [comment]
Next actions: 
- [x] ping Patrick about who owns the application 
- [x] draft answers to the questions.

**Comment by joereddington-public** [comment]
# Today's Sprint. 
- [ ] Write out your plan as it makes sense to you
- [ ] Work out how to fit that into the questions. 


## Write out the plan. 
### What do we know
* I understand that Collective Intelligence is: group intelligence.  You can increase collective intelligence in a group by organising them better; improving communication; and reducing friction. 
* Or indeed,  Collective intelligence is the intelligence of a collective.  
* "Nesta is offering grants of up to £20,000 for organisations to do this through practical experiments that will provide actionable and generalisable insights into good collective intelligence design." 

### What we believe 
* That White Water Writers  exhibits excellent collective intelligence
* that there are many fields that can learn form White Water Writer's use of collective intelligence. 
* That White Water Writers can be used to gain insight into social problems. "Evidence for the added value of using collective intelligence versus other approaches to address social challenges" 

We have a slight problem in that WWW is a fully operation design, and Nesta is looking for experiments.   Is there an experiment we would like to do? 

What are the insights that people should take from WWW for their own projects? 

- Artifact based
- Clear areas of ownership.  
-  Motivation.  

The application form is genuinely looking for a science experiment.  

So, here are four science experiments 
* Can collective intelligence work with novel writing (release successful book) 
* Can collective intelligence work with social problems through fiction.  
* Do AI technicquies improve the marketability of novels. 
* Can collective intelligence approaches change education effectively. 

I feel like the collective intellgience with social problems is the best shot. 


So, here's the experiment: 

**What do I want to find out:**
I want to find out if short intense collective intelligence sprints can provide more insight into major social problems than traditional long-term, shadow studies and, in particular, this can be achived by having people develop narratives around issues they have lived experience of.  

**What will I measure**
1. Write novel about X 
2. Conduct focus group about issues around X 
4. Focus group are shown their answers from the focus group, and extracts from novel and asked to rate both for honesty, impactfulness and how much the partipants feel the text reflects their position. 

How will I measure it: 



What will that tell us:

**Comment by joereddington-public** [comment]
Reviewing the information online again: 

"Collaboration with our team of researchers and commitment to careful research is critical. " 
"Make use of digital technologies/methods" 

Okay, need to rewrite the answers so that is extremely clear.

**Comment by joereddington-public** [comment]
This is the version without spelling mistakes. 

[Electric Wind God Fist .docx](https://github.com/eQualityTime/Public/files/2562653/Electric.Wind.God.Fist.docx)

**Comment by joereddington-public** [comment]
![screen shot 2018-11-08 at 16 51 52](https://user-images.githubusercontent.com/40637406/48213876-a9402700-e376-11e8-9cc1-a6aac2c94bc1.png)
