### ISSUE TITLE
Create Trustee Terms of Reference

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#55]
We need a trustee terms of reference so we can establish exactly what current trustees should be doing and so that new trustees know what they are doing.  

What are the steps? 
- [x] Find out if anyone else has this sort of document
- [x] Review existing versions. 
- [x] Review articles of incorportation
- [x] Sketch the main THINGs that would be useful. 
- [ ] Get lots of trustee input. 

Okay, so we know what the next action is.

**Comment by joereddington** [comment]
# Reviewing existing ones. 

1. http://oxfordshire.org/wp-content/uploads/2014/12/OCF-Trustee-Terms-of-Reference.pdf

Okay, so it has some good wording. I'm amused by 'every trustee must donate' but it also includes a 'what trustees can expect form us' I think that's interesting. Most importantly it includes some information on how to join the board and so on. 

2.  https://www.nuclearinst.com/write/MediaUploads/Trustee%20docs/BoT_ToR_RevA_161014.pdf

This is a list.  Only a list. Very listy. 

3.  https://www.landscapeinstitute.org/PDF/Contribute/TermsofReferenceBoardofTrustees_001.pdf 

Very general. Very nice.  It's making me think I should check our existing acts of incorportation because a lot of this STUFF is in there. 

I feel like the next action is to take one of the good ones of these, do some copy pasting and start rewriting entirely...

**Comment by joereddington-public** [comment]
First draft: 

DON'T LOOK AT THIS VERSION

> # Equality Time 
> ## Terms of reference for Trustees 
> 
> eQuality Time's trustees control every aspect of it's operation and the charity has been very lucky to have had a range of hardworking and dedicated Trustees. This document outlines the commitments expected of our trustees so that they are clear about the duties and responsibilities. 
DON'T LOOK AT THIS VERSION
> 
> ### Practical Expectations 
> eQuality Time trustees are responsibile for setting the direction of the charity and for ensuring that it's operations are carried out in an effective and legal way. 
DON'T LOOK AT THIS VERSION
> 
> In this, trustees have full access to all working files produced by the organsation, are sent a written briefing every two weeks, and hold a short (30 minute) meeting by Skype each month for them to ask questions of, and raise issues with, the Chief Operating Officer.  Minutes of previous meetings can be seen [here](https://www.dropbox.com/sh/cafqii2t3iefoex/AACeDX3pThe3EtDLmQRMxuhHa?dl=0). On a yearly basis, there is a longer meeting that includes more detailed discussion of topics.  
> 
DON'T LOOK AT THIS VERSION
> Operationally, the main action taken by trustees is the approval of payments from our bank account. Each trustee is given a login to our bank, Unity Bank, and periodically the trustees log in to check the pending payments against the documents that have been provided and approve (or not) the payments.  
> 
> ### Fundermental Expectations
> Trustees are required to ensure Trustees  must  familiarise  themselves  with  all  clauses  included  in our [articules of incorportation](http://equalitytime.co.uk/wp-content/uploads/2015/12/eQuality-Time-Arts-and-Mems.pdf) and must accept ultimate responsibility as appropriate for directing the affairs of the charity, and ensuring  that  it  is  solvent,  well run  and  delivering  its  charitable  outcomes  for  the benefit of the public.
> 
> ### Useful notes 
> The current Chair of eQuality Time is Clare Walsh 
> The current Secretary and COO of eQuality Time is Joseph Reddington. 

Next action is to check this with trustees.

**Comment by joereddington-public** [comment]
Second draft: 

> # Equality Time 
> ### Practical Expectations 
> eQuality Time trustees set the direction of the charity and make sure that it's work is done well, and properly.
> 
> They read a written report every two weeks, and set up a 30 minute meeting by Skype each month so they can make decisions and question the Chief Operating Officer.  Minutes of past meetings are [here](https://www.dropbox.com/sh/cafqii2t3iefoex/AACeDX3pThe3EtDLmQRMxuhHa?dl=0). Once a year there is a longer meeting.  So they can check any details at any time they have full access to all eQuality working files. 
> 
> The most practical job of trustees is to check payments from our bank account (for which they get all the supporting evidence).
> 
> Sometimes Trustee help is requested for particular projects - one is an expert in Software Engineering and one in  Creative Writing, and they are often asked for help in those areas of expertise.  Similarly trustees with lived experience of issues like disabiliy and mental health issues guide us in relevent projects. 

> 
> ### The Law 
> Trustees  must  familiarise  themselves  with  all  parts of our [articules of incorportation](http://equalitytime.co.uk/wp-content/uploads/2015/12/eQuality-Time-Arts-and-Mems.pdf) and must accept ultimate responsibility as appropriate for directing the affairs of the charity, and ensuring  that  it  is  solvent,  well run  and  delivering  its  charitable  outcomes  for  the benefit of the public.
> 
> ### Useful notes 
> The current Chair of eQuality Time is Clare Walsh 
> The current Secretary and COO of eQuality Time is Joseph Reddington.

**Comment by blaise17** [comment]
eQuality Time* working files.

articles* of incorporation

Might be useful to add the current treasurer?

**Comment by joereddington-public** [comment]
Yes. Will do. Thank you.

**Comment by joereddington** [comment]
On blog here: http://equalitytime.co.uk/6341/2019/04/03/trustee-terms-of-reference/
