### ISSUE TITLE
Send Trustees Application draft for Big Lottery Fund by 3rd December 

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#56]
# Resources 
[Main site](https://www.biglotteryfund.org.uk/blog/2018-10-26/our-new-digital-fund) 

# Plan 
- [ ] Read the document 
- [ ] choose project 
- [ ] get trustee application approval 
- [ ] draft answers

**Comment by joereddington-public** [comment]
Missed deadline.  

What to do better next time: 
* Be clearer about the deadline 
* Have a seperate task to inform trustees that you want to apply for something. 
* Do more public sprints!
