### ISSUE TITLE
Review Accountants

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#6]
We have an existing accountant at eQuality Time, who prepared the accounts who can find [here](http://equalitytime.co.uk/about-equality-time/), for which we paid approximatedly £780 per year. 

It's worth looking into other potential accountants periodically, hence this project. 

# Plan 
- [ ] Invite some Upwork freelancers to bid on the work.

**Comment by joereddington** [comment]
###### 03/07/18 08:44 to 08:54: 
Posted job on upwork. It is live [here](https://www.upwork.com/jobs/~01bb31a726a10cb0c9). That was pretty quick actually.  If we get some good applicatants we'll be going with them, otherwise the status quo is good to stand.

**Comment by joereddington** [comment]
###### 08/07/18 07:37: 
Reviewing proposals.  Some notes: 

* I should have specified I wanted knowledge of the UK system.
* I should have been much more particular about what I was looking for. 
* Many of the applicants haven't read the post. 

###### 07:41:
###### 07:51: 
Actually, I was very specific, most people hadn't read the post.  What I've now done is spent a few minutes doing a search and inviting specific people to apply to the job.

**Comment by joereddington** [comment]
###### 11/07/18 08:46: 
Let's have another look.  

###### 08:57: 
Okay, there is one I like, I've sent a message and the next action is to talk to trustees.

**Comment by joereddington-public** [comment]
They approved. Have hired.
