### ISSUE TITLE
Six month update report for Comic Relief by 1st January

### ISSUE THREAD

**Issue by joereddington-public** [eQualityTime/Public#66]
It's a nine month project, so six month report is quite far though. That means the deadline is...

**Comment by joereddington** [comment]
Okay, so there are two parts to this. One is the repot, the other is doing enought work that the report looks good.  

- [ ] Make a list of the sections we have to fill in. 
- [ ] Review the last report we had. 
- [ ] Get finantial statment on where we are. 
- [ ] Get the github done at the releast 
- [ ] get the changes made from the first interview.

**Comment by joereddington** [comment]
I submitted the form today: 
[cr_grants_managing_Six-month-update-form-and-guidance.docx](https://github.com/eQualityTime/Public/files/2718100/cr_grants_managing_Six-month-update-form-and-guidance.docx)

(Gem doesn't allow additional uploads so didn't do the financial report)
