### ISSUE TITLE
Prepare Google Talk by Febuary 15

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#68]
Joe gave a talk at [Confluence](https://bytethebook.com/event/confluence-in-partnership-with-googles-academy-london/) on Friday the 15th 2019.  

# The slides: 

# Lessons Learned
* I'd forgotten how important it is to reherse the timings - I ran over badly.  I also should have written the script out properly in advance. 
* Should have used my twitter a bit better. Met some nice people.

**Comment by joereddington-public** [comment]
Next action is Email to confirm time and details.

**Comment by joereddington** [comment]
[confluence.pptx](https://github.com/eQualityTime/Public/files/3117663/confluence.pptx)
