### ISSUE TITLE
Apply to the Ragdoll foundation

### ISSUE THREAD

**Issue by joereddington-public** [eQualityTime/Public#69]
[Site](http://www.ragdollfoundation.org.uk/portfolio/grant-giving) 

http://www.ragdollfoundation.org.uk/wp-content/uploads/2018/05/Guidance-for-OGS-Applicants-Revised-April-2018-FINAL.pdf

[Application form](http://www.ragdollfoundation.org.uk/wp-content/uploads/2018/05/ApplicationForm_RevisedApril2018.pdf)

**Comment by joereddington** [comment]
http://www.ragdollfoundation.org.uk/wp-content/uploads/2020/04/Main-Grants-Guidance-Notes.pdf - "Projects that effectively replace school provision" might be a bit of a problem for WWW, but fits for Supertitle - although struggles for arts" hmm.  Might be worth looking at the list of projects
