### ISSUE TITLE
Apply for  Entrepreneurship grant by midday 4th April 1st April

### ISSUE THREAD

**Issue by joereddington-public** [eQualityTime/Public#71]
https://mfip.org.uk/2018/11/16/funding-available-for-charitable-organisations-to-become-more-enterprising-june-2019-england/

But instead: 

https://www.sibgroup.org.uk/enterprise-grants

**Comment by joereddington** [comment]
* What is the geographical reach of your work? *
* How many beneficiaries you reach each year? *
* How many full time employees do you have? *
* How many volunteers work with you? *
* How many trustee/board members do you have? *
* Please describe the purpose of your organisation, and how you achieve this *
* (Maximum of 250 characters)
* Please tell us about your track record in achieving your purpose to date *
* (Maximum of 250 characters)
* How much surplus or profit did your organisation generate in your last full financial year? *
* What percentage of your income comes from grants? *
* What percentage of your income comes from fundraising or donations? *
* What percentage of your income comes from public sector contracts? *
* What percentage of your income is NOT from public sector contracts? *
* What percentage of your income is unrestricted in terms of its use? *
* Is your organisation already trading or thinking about trading? *
* To what extent will your current or proposed trading activity have a clear and specific link to your organisation's mission and purpose? *
* Please provide us with a description of the trading activity you wish to develop with the help of this grant? *
* (Maximum of 250 characters)
* How will this trading activity increase your financial resilience and create/maintain social impact for either homeless or young people? *
* (Maximum of 250 characters)
* Which type of grant do you wish to apply for? *

**Comment by joereddington** [comment]
Next action is to work thought those questions with regard to Quickbooks... Want to fix the invoices first though.

**Comment by joereddington** [comment]
No next action is to ring up with: 

Is comic relief a public sector contract 
Is this over one year or many years.

**Comment by joereddington** [comment]
I rang up.  It's 'all time'.  

Okay. I've spent some time with the Quickbooks, We've earned 108,683 in sales and 128 in grants. I can do the rest from here.

**Comment by joereddington** [comment]
Snot! Missed it. :(
