### ISSUE TITLE
Apply for https://planplasticfund.com/ by 24 Febuary 

### ISSUE THREAD

**Issue by joereddington-public** [eQualityTime/Public#72]
We have a new project [This is rubbish](https://github.com/eQualityTime/Public/issues/73).   We'd like to apply to [this funding scheme](https://planplasticfund.com/) with it. 

I missed the initial deadline, but noticed it was still open and have confirmed by phone that I have a little more time.  Not much more but... 
 
- [x] First tell Trustees 
- [x] Take 10 minutes to read though the documents to check that we are eligible. 
 * Unsure how to do the attachements properly here: https://planplasticfund.com/submit-your-project-1 
 - [x] Send documents by email as per step one 
 - [x] Create the pretty print comment on this issue.
 - [x] Bullet point the answers in the pretty print. 
 - [ ] create video 
    - [x] Look at [advice](https://static1.squarespace.com/static/5c2f92fb9772aee521a2469a/t/5c48848c0ebbe8f531d13981/1548256401724/Plan+Plastic+Video+Tips.pdf) 
    - [x] do the brainstorm of the script.
   -  [x] POssibly ask for help.
   - [x] Write script for Kat. 
   - [ ] Track down the references, headlines, and screenshot them 
  -  [ ] Get photos 
 - [ ] Get the template you used for the other shots
 -  [ ] Do filming.     
 - [x] Draft answers 
    - [x] Go and get the information from the most recent arts council submission.  
 - [ ] Put answers thought simplewriter
 - [ ] Create budget 
    - [x] first draft 
    - [ ] research costs and get douple quotes 
    - [ ] adjust budget for timings 
   -  [ ] add gant chart. 
 - [ ] Draft the missing bits 
 - [ ] Send to proofreaders 
 - [ ] Review, see where you are. 
 - [ ] Submit

**Comment by joereddington-public** [comment]
# Step 1 
Email: 

> Subject: This Is Rubbish Plan Plastic Application 2019
> Content: 
> 
> Dear Hubbub, 
> 
> Please find attached our due dilligence files for the plan plastic application. 
> 
> - Our Accounts document: Audit_This_is_Rubbish_Joe_Reddington_2019
> - Evidence of being a constituted body: Evidence_This_is_Rubbish_Joe_Reddington_2019
> 
> As part of our commitment to transparency, you can also find these documents on our [about us page](http://equalitytime.co.uk/about-equality-time/). 
> 
> Please note - as per previous corrspondence, our accounts are not yet audited.


# Step 2
Application form. 

1. How much are you applying for in £? *
_We expect to fund projects for between £150,000 and £300,000 each. However, if you wish to apply for more or less than this, please state why._

* Do budget first 

2. What is the minimum amount of funding you can accept for this project to still go ahead? (in £) *

* Do budget first 

3. Have you had funding committed from elsewhere for the same project? If so, to what value? *
_This fund is intended to be majority or whole funding for a project._
No funding from elsewhere. 


4. Tell us about your organisation (and any partner organisations). *
(Max 200 words)

Since 2014 eQuality Time has delivered research-lead projects for social good. Its recent achievements include: winning the 2015 Inclusive Technology Prize; being named in the 2016 Nominet top 100, alongside projects like #blacklivesmatter and Well Told Story; and being part of the 2018 Comic Relief Tech for Good Cohort.

Our plan has been to build a wide portfolio of different interventions covering radically different problems, and balanced between long and short term, and based on a variety of different income streams. Our projects include creative writing camps that schools pay for directly; projects that help prisoners connect with their young children paid for from prison budgets; and the development of assitive technology for disabled people paid for from grants.  Our longest running projects have moved from being grant supported to generating the majority of our running costs. 

What unites our projects is a commitment to open design and transparency, as well as designing projects that inventivise end-users to work together for a common goal. 


5. Describe your project and tell us how it will reduce plastic pollution. Explain how it addresses one of the five focus areas listed. *
_(Max 300 words) _Please visit, 'What we're looking for', to read more about the five focus areas. All shortlisted projects will be asked to submit a project plan and demonstrate that they will be in a position to commence the project in June 2019.__ 

The two major problems with plastic recycling in the UK are consumers aren't recycling enough (https://www.green-alliance.org.uk/resources/A%20zero%20waste%20UK.pdf), and when they do, they are doing it badly (https://www.britishscienceassociation.org/news/british-science-week-lifts-the-lid-on-recycling-misconceptions). Repeated studies have shown that domestic behaviours are most influenced by the actions of neighbours and by providing a simple reward structure.
"This is rubbish" works by establishing a review and reward system locally. Personal reports from our staff help people understand their own recycling choices better, and follow up visits give an incentive to improve. By giving out 'reward' stickers for residents to put on their bins and by using a staggered visiting schedule over an area, we can promote a level of competitiveness within an area and thus get more people to make long term behavioural changes.
Alongside campaigns in local schools to raise awareness and inspire children, this creates impactful behaviour change that is rooted in well-established research that has been applied successfully in other areas such as reducing heating costs. ( https://www.researchgate.net/publication/5305895_Normative_Social_Influence_Is_Underdetected) 


6. Tell us why the individuals on the project team and your organisation are the best to deliver this project, including your track record for effective project management. *
 (Max 300 words).

eQuality Time has recent experience of managing grant-funded projects - most recently, £48,500 from Comic Relief, and £62,000 from Nesta. eQuality Time has a mix of restricted and unrestricted funding and as projects mature and become sustainable there is an increase in earned income. Our licencing of IP to Keele University has produced £15,000 unrestricted income in the last year and we expect to continue.
Our trustees have significant experience in recycling and environmental management: Seb Junemann is an energy researcher at UCL with an interest in socio-technical research in domestic buildings. He previously worked for NatCen as Research Director of the Energy and Environment team. Tess Reddington founded and run Phil The Box, a recycling company, in 2011, and has extensive experience working with local authorities on recycling projects. At the same time our COO Dr Joseph Reddington has proven expertise in delivering projects for long term behavioural change.

From a finance perspective, eQuality Time's COO is a member of ACCA and is currently completing a chartered accountancy qualification.
eQuality Time's accountant (TLL) has specialist knowledge of the third sector. Our accounts are prepared in Quickbooks and all expenditure decisions are made at committee meetings and all payments require two signatories. Our Delegated Authority policy states that purchases over the value of £1,500 require two quotations to be obtained to ensure value for money. Source documents for all transactions are retained. Income and expenditure are allocated to a budget heading and to a fund to ensure accounting separation. Bank reconciliations are prepared monthly.
Overhead costs are budgeted for annually and we aim to ensure all projects achieve 'full cost recovery’.




7. What impact will your project have on plastic pollution in the short medium and/ or long term? Tell us what your outcomes and indicators of success will be. *
_(Max 300 word)_
• A greater volume of recycling is received by the local authority in our target area.
• The recycling that the local authority receives is of a higher grade, and the grade of recycling remains high six months later.
• The project is conducted in a way that is scientifically rigorous enough to affect public policy.
Our indicators of success are:
For the outcome: “A greater volume of recycling is received by the local authority in our target area” our indicators of success are “The average total weight of recycling in our follow up visits to a property is significantly higher than the average total weight of recycling in our initial visit to a property.”
For the outcome: “The recycling that the local authority receives is of a higher grade, and that the grade of recycling remains high six months later,” the indicator of success is “the average grade (given by our staff) of a property’s recycling is higher on the second visit than on the first, and the grade of recycling given on a final six month visit is closer to the second visit than the first.”
For the outcome: “The project is conducted in a way that is scientifically rigorous enough to affect public policy,” the indicator of success is “Publication of findings in a peer reviewed academic outlet that can be disseminated to local authorities and funders.”
 

8. Tell us about any wider social or environmental benefits your project is likely to bring. *
 (Max 200 words).

In the wider context, our project will improve all recycling, not just plastic. Moreover, its competitive element will engage people who would not normally be sympathetic with environmental issues to start making positive contributions. Repeated research shows that when an individual starts acting as if they have a particular set of beliefs, they begin to also hold those beliefs. By structuring this project in this way, we have a chance to reach the most reluctant residents and improve their behaviour.


9. How will you ensure that the project creates a legacy, and continues to have impact beyond the funded year of the project? *
(Max 300 words).

Our project design is entirely focused on the long term maintenance of an immediate change for beyond the project. Our key outcome is "“The recycling that the local authority receives is of a higher grade, and that the grade of recycling remains high six months later,” and our indicators are designed so that it's the long term change we are measuring. We've been careful to base this project design on research which looks at long term behavioural change and, as an example, we have even gone to the extent of checking the rate at which people change the contents of their weekly shop to see if this would affect the reports we should give them.



10. How will you share the learnings, outputs and results widely? *
(Max 300 words).

Firstly we disseminate to other third sector organisations: “This is what we did, this are the results, this is how you would do the same”. Our staff and trustees regularly present at venues ranging from TEDx events to Tech for Good conferences.
Secondly, we disseminate academically. The COO Dr Joseph Reddington is a former academic and continues to work with contacts to publish the results of eQuality Time projects in a scientifically rigorous way. Being able to both draw from current research, and design projects in such a way that their results are clear, is a key strength of eQuality Time as an organisation. In particular, our trustee Seb Junemann is an academic researcher working directly on the topic of socio-technical research in domestic buildings – this project utilises his strengths and he worked with us to design it effectively.
This academic output leads into the third strand – public policy. By providing clearly written briefings that are backed up by peer reviewed data, we can be more influential over local authority policy than many other organisations. We hope to be able to make the case to the local authority that it is cost effective to run this sort of project because the value of the recycling that is collected is raised so significantly over the long term.


11. Provide a budget showing how you would spend the grant money applied for. *

Done.

**Comment by joereddington-public** [comment]
Doing the budget.  

Starting with the arts council budget as a starting point.

**Comment by joereddington-public** [comment]
Video Script: 

* Heartrending
* The problem
* Our solution 
* Who we are

I worte it as a power point: 
[pitch script. .pptx](https://github.com/eQualityTime/Public/files/2905544/pitch.script.pptx)

Script for my bit: 
[Untitled.pdf](https://github.com/eQualityTime/Public/files/2905598/Untitled.pdf)


> Ask for Facebook! 
> 
> Hello everbody! I need a bit of help!   Remember I was looking for names for a recycling project a while back (X won with 'This is Rubbish', Y was runner up with 'Junk and disorderly') - I'm putting to gether a funding proposal for it and I find I need to make a two minute video.  But I'm a little short of footage of the 'problem'.  So, you know when you are putting something in the recycling and you think "Hang on, which bin should this go in?" And you're a bit confused for a bit before randomly throwing it in one? I need some three second clips of people doing that. Bonus points if you throw it into the wrong bin...    I'm going to put them all together so the funders have something to watch while the voiceover talks about the problem.   Any takers? 


Next actions

**Comment by joereddington-public** [comment]
Back of envelope budget: 


Item | Projected Cost
-- | --
Recrutiment   of faciliators | £          2,000
Faciliator   salary | £      100,000
Faciliator   training | £          5,000
Vechieral   hire/purchase and refitting | £        10,000
Report   and branding design | £          5,000
Public   media work | £        10,000
Project manager  0.5FT (6months) | £        20,000
Insurance | £          2,000
Equipment | £          3,000
Office costs; phone, internet, printing,   sundries, admin service, postage | £        10,000
Accountants | £             800
Core costs | £        15,000
Total | £      182,800

**Comment by joereddington-public** [comment]
I think at this stage there is about 7 hours work left in this. 
2.5 on video 
1 on doing answers 
1 on revising answers 
1 on general faff
1 on budget redo. 

In terms of the timing -  I need to get the footage tonight. I also need to do the writing tonight so that someone can review it if they get a chance tomorrow.  

So actually. In terms of getting it right. The big rock to move as soon as possible is the filming. Then do the video first cut at least. That's a good nights work.  

On the other hand, the video doesn't need proofreading so if we have a proofreader, it would be best to get the text done first. Hmm.  

Next action - ask for a proofreader...

**Comment by joereddington** [comment]
Some potential content: 

> This is a single organisation application and we take full responsbility for it:
> All members of the eQuality Time team have extensive experience of both event management and the novel writing process. Significantly, eQuality Time has produced over 80 novels with groups from schools, universities, hospises, and special units, developing the software and horning the techniques to be used in the DISCORD project, which will our first aimed at commercial and critical success (the others were aimed at writer development).
> Regarding the media facing aspects of the work, we have dealt with a variety of significant media events in the past 12 months including being the winner of the £50,000 Nesta Inclusive Prize and being chosen as one of the 2016 Nominet 100 projects for social good. We have also budgeted for extra resources from a media agency we have close links with.
> Our links with publishers and agents are evidenced by the recommendation letter attached to this application.


> eQuality Time has recent experience of managing grant-funded projects Most recently £48,500 from Comic Relief, and £62,000 from Nesta. eQuality Time has a mix of restricted and unrestricted funding and as projects mature and become sustainable there is an increase in earned income. Our licencing of IP to Keele University has produced £15,000 unrestricted income in the last year and we expect to continue.
> Our Treasurer has significant budget management experience managing a budget of over £100,000 pa with Burscough Parish Council which is subject to strict budget controls and external audit. She also has significant experience of budgeting in the social enterprise sector, having founded and run three organisations including West Lancs Positive Living (charity).
> The COO is a member of ACCA and is currently completing a chartered accountancy qualification.
> eQuality Time's accountant (TLL) has specialist knowledge of the third sector. Our accounts are prepared in Quickbooks and all expenditure decisions are made at committee meetings and all payments require two signatories. Our Delegated Authority policy states that purchases over the value of £1,500 require two quotations to be obtained to ensure value for money. Source documents for all transactions are retained. Income and expenditure are allocated to a budget heading and to a fund to ensure accounting separation. Bank reconciliations are prepared monthly.
> Overhead costs are budgeted for annually and we aim to ensure all projects achieve 'full cost recovery’.


....

>  eQuality Time's recent achievements include: winning the 2015 Inclusive Technology Prize
> being named in the 2016 Nominet top 100, alongside projects like #blacklivesmatter and Well Told Story.
> Producing over 80 novels with 800 young people with our creative writing intervention White Water Writers (whitewaterwriters.com).
> Winning and delivering the tender for providing an artistic installation for Bath Spa’s MIX conference on the theme of creative writing.
> The key team members for this project, who will also interview and select the project's writers are:
> Dr Joe Reddington, a designer with a focus on inclusion and creativity. His art projects include the 418 teapot (http://goo.gl/Wf3056), and Flowers for Turing (http://goo.gl/nNrdtf). He pioneered group novel writing interventions to improve outcomes. In the process he produced over 80 novels with groups from schools, universities, hospises, and special units, developing the software and horning the techniques to be used in the BATTLECRY project.
> Dr Douglas Cowie is an American novelist and senior lecturer in creative writing at Royal Holloway, University of London. He is the author of Owen Noone and the Marauder (Canongate 2005), Sing for Life: Tin Pan Alley (Black Hill Press 2013), Sing for Life: Away, You Rolling River (Black Hill Press 2014), and Noon in Paris, Eight in Chicago (Myriad Editions 2016).
> Francesca Baker is a journalist, events organiser, and marketer. She is founder and creator of Let’s Tell Stories, a space to read and write to inspire and learn and produced the book Eating and Living (2016).

**Comment by joereddington** [comment]
## 26/02/19 14:44 to 16:18  
Some solid work putting in the draft answers.  Some are short, some need a bit of a review, but they are in.  Look a lot longer than I estimated above though.   

Next action: 

Revise the budget.  Need better estimates of cost with notes attached to them. Also include the stuff from the green book about clever adjustments.

**Comment by joereddington** [comment]
Filming has been done this evening. It's going to be a little bit tricky to edit down to be honest.  I don't think I have time for everything I wanted to do...  Next action is a rough edit (after all the one after this might be a five minute version) and then I'll work out cutting it down.

**Comment by joereddington** [comment]
## 27/02/19 11:26 to 12:32,  (A) due:2019-02-27 Sprint editing for: [200~https://github.com/eQualityTime/Public/issues/72
Doing movie editing.

![d0amejgwwaahubs](https://user-images.githubusercontent.com/4369547/53494250-337ed900-3a95-11e9-99d0-85f3ff0759f8.jpg)

**Comment by joereddington** [comment]
## 27/02/19 13:18 to 14:32, Submitted! 
![d0a0b_ox0aalq_p](https://user-images.githubusercontent.com/4369547/53499946-57481c00-3aa1-11e9-8289-753efb296995.jpg)

**Comment by joereddington** [comment]
Done! 

# If I was doing this again... 
* Spend more time on the budget, and produce the gantt chart to go with. 
* Apply sooner! 
* More proofreading
* I'm a little unhappy with the video, I think it needed a *sorting* shot, but there is only so much you can put in...

**Comment by joereddington-public** [comment]
This is blogged at: http://equalitytime.co.uk/6380/2019/11/14/this-is-rubbish/ 
The youtube video is: https://www.youtube.com/watch?v=t8ZGypzcud0
