### ISSUE TITLE
Develop Recycling Project

### ISSUE THREAD

**Issue by joereddington-public** [eQualityTime/Public#73]
# Most recent attempt 

*This is rubbish* increases recycling in a local area by working face-to-face with residents to increase the transparency of the process. 

British People are bad at recycling: both in terms of quality (we put the wrong THINGs in the wrong boxes) and quantity (we don't put much in the boxes). Our project sends people door-to-door in a local area to gently chat with people about recycling, and help them sort their existing shopping.  On a follow up visit, people get a badge they can stick on their bin to show their improvement.  Motivated by their own badgers, and those of their neighbours, recycling amounts and quality increases - particularly because people repeatedly buy the same products, so a small amount of targeted intervention, is a lot more useful than current practice. 

# Background 
> People don't really understand how to recycle. They put waste in the wrong boxes.  A lot.  If people understood which bits of their waste was meant to go into which boxes, then recycling would be vastly improved. 
> 
> The second problem is that lots of people in the UK don't take recycling that seriously.  We rank near the bottom of europe on waste recycled.
> 
> So we don't recycle much, and when we do we do it badly. Let's try and fix both.  
> 
> It's know that the best way to get people to use less power is to tell them that their neighbours use less.    We think we can do the same with recycling.  But we'd have to know how much their neighbours were recycling. So we should go and talk to them.  And if we are talking to them, then we can make it quietly competitive. 

We should make it into a full project proposal. 

## User perspective
* Nice person with clipboard turns up to the house.  Asks about recycling. Gets you to say you want to recycle more but aren't sure what needs recycling.  Gives a sample recycling report and offers a free review - they'll come to the outside of your house before the next bin delivery and go through it quickly.  User signs a disclaimer. Reassured about identity theft. 
* A week later they get posted (because you have address and don't need other details) a quick report saying "Hey you don't need this recycled, but it's great that this one is". 
* Two week's later they get another report telling them how much they have improved and they get a set of stickers for their bin.  

The user is now motivated to recycle more, and will recycle much better.  

# Plan
- [ ] Get the background material and quotes 
- [ ] Write up the process
- [ ] Do the simplewriter version. 
- [ ] send off
- [ ] do blog post.

**Comment by joereddington-public** [comment]
From [this ted talk](https://www.ted.com/talks/alex_laskey_how_behavioral_science_can_lower_your_energy_bill/transcript) 

> [In an experiment in] in San Marcos, California. Graduate students put signs on every door in a neighborhood, asking people to turn off their air conditioning and turn on their fans. One quarter of the homes received a message that said, did you know you could save 54 dollars a month this summer? Turn off your air conditioning, turn on your fans. Another group got an environmental message. And still a third group got a message about being good citizens, preventing blackouts. Most people guessed that money-saving message would work best of all. In fact, none of these messages worked. They had zero impact on energy consumption. It was as if the grad students hadn't shown up at all.
> 
> But there was a fourth message, and this message simply said, "When surveyed, 77 percent of your neighbors said that they turned off their air conditioning and turned on their fans. Please join them. Turn off your air conditioning and turn on your fans." And wouldn't you know it, they did. The people who received this message showed a marked decrease in energy consumption simply by being told what their neighbors were doing.

The question is: can we do this with recycling.  Both the amount, and the quality of the recycling.  

What I need is a source that says "British people are bad at recycling"

Turns out there are lots: 
* https://inews.co.uk/news/environment/brits-not-knowing-recycling/
* https://www.express.co.uk/news/science/932589/recycling-environment-confused-nature-Britons-recycle-unsuccessfully (check if the same study) 
*https://www.independent.co.uk/environment/britains-recycling-record-among-the-worst-in-europe-413647.html 
* https://news.sky.com/story/recycling-could-be-doing-more-harm-than-good-11291742

I could also do with quotes from the people who sort it at the recycling centre - what are the big complaints. 

Okay, so there is some supporting evidence.  Great. So here is what we want to do: 

Increase recycling by putting people into competition with their neightbours and by reviewing their bins.   

Process goes in this order
* Select and area 
* Randomly select houses in area. 
* Pop around for a survay with a value add (maybe the heat camera)  - ask people about recycling and see if they want an inspection. Give them a sample inspection report. Offer to do one the day before the bins are collected. 
* Do the reports, give people the report and a badge for the bins. 
* Do the next week's recycling inpsection as well. 
* Then survay people. 

### From the point of the some users: 
* Nice person with clipboard turns up to the house.  Asks about recycling. Gets you to say you want to recycle more but aren't sure what needs recycling.  Gives a sample recycling report and offers a free review - they'll come to the outside of your house before the next bin delivery and go through it quickly.  User signs a disclaimer. Reassured about identity theft. 
* A week later they get posted (because you have address and don't need other details) a quick report saying "Hey you don't need this recycled, but it's great that this one is". 
* Two week's later they get another report telling them how much they have improved and they get a set of stickers for their bin.  

#### From the point of view of other users
* They see some stickers on other bins and it eats at them. 
* A nice person with a clipboard turns out and talks about how neightbours have doubled their recycling in the last few weeks.  
* Cont.

**Comment by joereddington** [comment]
Short version: 


> People don't really understand how to recycle. They put waste in the wrong boxes.  A lot.  If people understood which bits of their waste was meant to go into which boxes, then recycling would be vastly improved. 
> 
> The second problem is that lots of people in the UK don't take recycling that seriously.  We rank near the bottom of europe on waste recycled.
> 
> So we don't recycle much, and when we do we do it badly. Let's try and fix both.  
> 
> It's know that the best way to get people to use less power is to tell them that their neighbours use less.    We think we can do the same with recycling.  But we'd have to know how much their neighbours were recycling. So we should go and talk to them.  And if we are talking to them, then we can make it quietly competitive.

**Comment by joereddington-public** [comment]
I've been trying to rewrite this for the blog and it's been difficult, so I'm reducing it to the single concept and doing an FAQ: 

"Meet Sam. Sam wants to recycle, but keeps putting rubbish in the wrong boxes. Sam mostly buys the same things every week, so when Alice came to his house and showed him how to sort one of his bins properly it meant it got it right for years to come."

Ha! Better idea, write it as a facebook post and get the FAQ done for you.

**Comment by joereddington** [comment]
put it here: https://www.facebook.com/joe.reddington/posts/10100859962052960

**Comment by joereddington-public** [comment]
Now blogged at: http://equalitytime.co.uk/6380/2019/11/14/this-is-rubbish/
