### ISSUE TITLE
Write IMPS 2.0

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#77]
We are outgrowing Google Drive at the same time that it is making itself harder for us to use.  Increasingly groups are finding it harder and harder to log in. 

It's time for us to have an alternative, either as a backup, or as a complete replacement. 

We're going to base our client on etherpad-lite. 
I created this issue: https://github.com/ether/etherpad-lite/issues/3599, which has been fufillied.  

# Plan 
- [x] Bring the repo into eQuality Time Github (2min, offline) 
- [x] Test existing scripts from current server (10minutes, offline) 
- [x] create folder on www.whitewaterwriters.com for IMPS 2.0 (2 min,offline) 
- [x] clone and fork IMPS, (2 min offline) 
- [x] Write setup script for creating new sprint. (30 minutes) 
Is this part of IMPS? Does the zombie files stay with it? Yes I think so, because they will change as IMPS does. 
- [x] port IMPS to use the etherpad-lite connectors. 
- [x] Create new Dashboard to view files. 
- [x] write the 'deploy' script for IMPS 2.0
- [x] Check you understand the notes from Joas 
- [ ] Email Joas with notes. 
- [x] create the new domain in dreamhost.
- [x] Clone the IMPS2 files to http://oracle.whitewaterwriters.com/
- [x] Get driver working. 

# Notes
* We use [Digital Occean](https://www.digitalocean.com/) to host the etherpad server itself at  while the rest of the code continues to sit in Dreamhost.  
* I've populated http://159.65.86.244/p/homer001 thought to about homer010 as test files. 
* I'm setting up http://oracle.whitewaterwriters.com/ as the site for the new approach.

**Comment by joereddington-public** [comment]
I've done some work on this today moving the scripts into python.

**Comment by joereddington** [comment]
Commands to test from Joas. 

> 1. Restarting the Etherpad container
> 
> 1. cd etherpad-joe 
> 2. eval "$(docker-machine --storage-path /usr/local/share/equality-job/docker-machines/ env etherpad-staging)"
> 3. docker-compose restart etherpad-staging 
> 
> The step 3 will restart the container that etherpad runs. 
> 
> 
> 2. Other alternative - Deploying 
> 
> Another way to solve it, it is doing a deploy. This will force all the containers restart
> 
> 1. cd etherpad-joe 
> 2. ./bin/deploy_to_staging.sh
>

**Comment by joereddington** [comment]
## 31/07/19 10:08 to 10:46
* Updating the issue and remapping. 
* Testing the digital occean scripts and writing response to Joas
* Working out launch dates with Richard. 
* Tiny postman interupt. 
* Create the oracle.whitewaterwriters.com site with barbara gordon as the access. Generated password is in lastpass. Have to wait for the rest of the code to catch up.   

![Screenshot 2019-07-31 at 10 25 32](https://user-images.githubusercontent.com/4369547/62202585-782ed900-b381-11e9-8157-49db34f21e18.png)
![Screenshot 2019-07-31 at 10 39 24](https://user-images.githubusercontent.com/4369547/62202589-79f89c80-b381-11e9-82cc-5ee3746d84c5.png)


> Hi Joas, 
> 
> I gave the commands a go, got a bit confused. I'm logging into the 'etherpad-staging' droplet via 'Access Console', but I'm struggling to find any of the folders/scripts you mention: "find . | grep joe" and "find . | grep deploy" return zero results.  Am I missing something obvious? 
> 
> Joe 

Nothing to do for a bit until the DNS comes thought, then the next action is to ssh barbaragordon@oracle.whitewaterwriters.com and clone the IMPS2 repo from /home/toomanycooks/whitewaterwriters.com/IMPS2/IMPS/workingDirectory

**Comment by joereddington** [comment]
## 19/08/19 14:51 to 15:46, Changing plans - moving to WWW for a full deployment.  
Interupt for urgent work - preparing IMPS2 for possible deployment. In the process I found out it wasn't quite as ready as I thought it was but that's okay, I've fixed a few bugs around it. In particular: 

* Create.py now takes and argument and also includes the info file 
* I've fixed a bug with full.html not showing the right files (it's tag dependent, so doesn't *really* need to be an individual file) 
* I've moved everything over to Oracle and possibly learned to spell it. 

More to do: 
* A proper Driver file that includes the ability to create. 
* Check the Latex is working 
* A cron for updates. 
* Work out why the site isn't showing up on my laptop but is on my phone
* Fix that there are two seperate repos for IMPS.git 

The last commit was: [etherpad 01c8dfd]

**Comment by joereddington** [comment]
There are linked issues: #96  is writing an abort code, and importantly we need to make sure (though Joas) that we actually can switch the code off and on again...

**Comment by joereddington** [comment]
Richard is reviewing the current set of code, but I also need to keep checking in with Joas, that's the thing that's holding me back.

**Comment by joereddington** [comment]
PAUSED for virus

**Comment by joereddington** [comment]
The main thing slowing this down is that I don't entirely trust the server system. I don't particularly like dreamhost either.  I have some learning to do, but... 

The next action is to properly rubberduck the problem on facebook.

**Comment by joereddington** [comment]
The Next action is to set up a server on Amazon, but that's definately not a task for today.

**Comment by joereddington** [comment]
Replaced by #150
