### ISSUE TITLE
Submit project "ECHO" to Arts Council.

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#78]
![Screenshot 2019-04-30 at 10 45 12](https://user-images.githubusercontent.com/4369547/56955437-4ff0cd80-6b39-11e9-9ffe-c84f02c194cb.png)

Our [ninth application](https://github.com/eQualityTime/Public/issues/59)(codename: "Discord") to the arts council was rejected. This means it is time to start our tenth. Which we shall call "ECHO" 

The [feedback](https://github.com/eQualityTime/Public/files/3130775/export-2.pdf) was a little vauge but wanted more details on the TooManyCooks process itself. 

# Resources
* [The site](https://applications.artscouncil.org.uk/)

# Plan 
- [x] Pick a codename: "Echo" 
- [x] Highlighter on the export to see which other aspects we can do. 
- [x] Create files for "Echo"
  - [x] Go throught Echo documents, check up to date and: 
  - [ ] Read through existing answers to find: 
       * Places were we can use the summary from the arts council feedback. 
       * Places were we can talk about the TooManyCooks process. 
       * Other places that we can make improvements. 
- [ ] Process and submit.

**Comment by joereddington-public** [comment]
Okay, the last time I got feedback at this level of detail was October 2017. That's embarassing.  

At the time it was "met" for all catagories, with this detail:  

Your application was not successful mainly because:

> 
> ** Comparatively weaker – management
> - We decided that the plans to manage your activity were less strong than other applications we received.
> 
> ** Comparatively weaker – public engagement
> - We decided that the public engagement outcomes of your activity were less strong than other applications we received.

This time the rates were "met" for everything and "strong" for management. That's good. 

I've reviewed the feedback.  There are no comments on the finance aspects, but there are some questions in terms of 'quality'.  One point I did want to think about was using the arts council 'summaries' in the next application: it is how they word things anyway.

**Comment by joereddington** [comment]
We appear to have lost some of the files, these are the last versions I have (some are from Codex and some are from Discord) 

[ECHO  arts project.docx](https://github.com/eQualityTime/Public/files/3251571/ECHO.arts.project.docx)
[ECHO Audience Development Plan.docx](https://github.com/eQualityTime/Public/files/3251572/ECHO.Audience.Development.Plan.docx)
[ECHO budget.xlsx](https://github.com/eQualityTime/Public/files/3251573/ECHO.budget.xlsx)
Done! The final version is: 
[Discord final submission](https://github.com/eQualityTime/Public/files/2906108/export-1.pdf)

WARNING! 
The main answers file is one version behind and WON'T be as up to date as the exported pdf.

**Comment by joereddington-public** [comment]
[ECHO.Audience.Development.Plan.docx (with FAQ bit)](https://github.com/eQualityTime/Public/files/3271519/ECHO.Audience.Development.Plan.docx)

**Comment by joereddington-public** [comment]
So I've been filling out the online form today.   There are several things to wait for: 

* The most recent accounts 
* The most recent turnover. 

I also need to use the other account to add the other attachement. Sad. 

I've brought all the submission files up to date and they are: 
[ECHO.Audience.Development.Plan.docx (with FAQ bit)](https://github.com/eQualityTime/Public/files/3271519/ECHO.Audience.Development.Plan.docx)
[ECHO - TOOMANYCOOKS.budget.xlsx](https://github.com/eQualityTime/Public/files/3271639/ECHO.-.TOOMANYCOOKS.budget.xlsx)
[ECHO.arts.project.docx](https://github.com/eQualityTime/Public/files/3271672/ECHO.arts.project.docx)

The online form itself is now mostly filled in: it is waiting for various attachements and details from accountants. 

![Screenshot 2019-06-10 at 11 33 03](https://user-images.githubusercontent.com/40637406/59190003-8c214000-8b73-11e9-9841-faef969bdda9.png)

**Comment by joereddington** [comment]
It's complete (I think)-  waiting for new accounts to send off.

**Comment by joereddington** [comment]
**"This e.Form has been submitted"**

## 31/07/19 09:44 to 10:00,
Very short final step - checking the finance details and uploading attachements.  Done.
