### ISSUE TITLE
Review and release new Expenditure against Grant Documents

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#8]
We've grown a lot in the last few months - in particular we're starting to receive a lot more 'unrestricted' funding, which lets us grow some of the core parts of the organisation.  

This makes it a sensible time to look at how we do our internal accounting.  Up until this point, we've had, effectively two sets of accounts. One that is the standard set of accounts given to an accountant, which keeps track of who has been paid and when they have been paid and so on. The other is the 'Expenditure against Grant' file, which I use to keep track of which bits of ring fenced money has been spent for which funder and which result. 

There's obviously a lot of overhead involved in maintaining two seperate sets of accounts, and it's time for me to do a bit of a process redesign so that at least one of them is automatic.  

# Brainstorming 
* Explore cash book - see if we can find a way of automatically generating the expenditure against grant with an extra column (going to be very tricky when an invoice is for multiple catagories) 
* So every ringfenced item within a project will need a unique EQT-wide code (which presumably is the name of the project, the name of the funder, the year of issue and the ringfenced amount)
* We *might* be able to deal with the fact some payments need spliting by giving them the code 'SPLIT' having a manually entered sheet called 'SPLIT' and checking the invoices add up properly. 

# Plan 
- [x] go through plan with TJR
- [x] Create 'expenditure against grant' sheet in cashbook
- [x] work out spending codes 
- [x] Add colum and start filling in spending codes. 
- [x] Put forumla into the expenditure against grant sheet 
- [ ] add checking equasions 
- [ ] sort the rest of the 'to sort' work.
- [x] add the historial data (spend before 31st August 2017)
- [x] after the historical data is in you should make sure the comic relief budget is assigned correctly (some of the budget goes into Nesta) 
- [ ] create spliting sheet
- [ ] populate spliting sheet. 
- [ ] present to Trustees

**Comment by joereddington** [comment]
###### 15/06/18 09:38 to 09:59: 
Working out the project design. Next action is to call TJR.

**Comment by joereddington** [comment]
###### 04/07/18 10:33: 
Let's open the cashbook.

###### 10:40: 
I've added a column and started the process. The next action is to copy some catagories over from the other file.  But alarm has gone off now.

**Comment by joereddington** [comment]
###### 08/07/18 15:45 to 16:11

I've started to populate the new sheet, but I've come accross some oddities with the cash book that need to be sorted.  I've drafted an email to  TJR. 

Some next action in the meantime 

- [ ] addd the comic relief catagories 
- [ ] add the shine catagories 
- [ ] Resolve the media wall into core, and create a way of dealing with core.

**Comment by joereddington** [comment]
###### 15/07/18 14:15 to 15:29: 
I've been over this, I've added a bunch more spending catagories and also sorted out the income catagories.  I've decided to keep the WWW accounts seperate for now (because they are at different levels of abstration), and we're most of the way there.  

###### 15:32: 
The next action is to sort the rest of the 'to sort' informaiton.

**Comment by joereddington-public** [comment]
Hmmm.  Our accountant is currently looking at the cash book, so it might be best to stay out of his way.

**Comment by joereddington-public** [comment]
The accountant has given us the cash book back and it looks good, I'm going to have a call with him. 

- [x] 1, 10, "Arrange call with accountant so that you can do expenditure against grant", 18-08-09 15:11
- [x] 1, 10, "Send set of unity statements to Accountant", 18-08-09 15:12

**Comment by joereddington-public** [comment]
Next action is to copy the expensiture sheet Joe prepared into the new sheet from accountant.

**Comment by joereddington-public** [comment]
I've done some serious work on this over the last few days and it's in good shame. Next actions are

(A) tell treasurer about new cash book
(C) Sort all the 'to sort' spending in the right categories in the expenditure against grant file. 
(C) put in checking sums into expenditure against grant so we can tell if something is missing.
(A) send new cashbook to accountant before meeting.

**Comment by joereddington** [comment]
This has been superceeded by the QuickBooks work. Closing
