### ISSUE TITLE
Match funding for Superhero Cyborg

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#89]
# Public Project 
Bringing [this](http://equalitytime.co.uk/4634/2015/01/05/superhero-cyborgs-surprisingly-even-cooler-than-it-sounds/) cool project to the UK would cost about £20k and we've got a Northern Irish funder who is willing to fund £10k of that, providing it runs in Northern Ireland. This is excellent, but it means that I've got only a few months to find the other £10k.  We've got a cool hackspace that will host us very cheaply, and various related charities that are willing to send participants our way, but we need to pay for things.  

## Resources 
* Here's the [application we made to the funder]()
* Here's the [hackspace we are working with](https://www.farsetlabs.org.uk/)
* This is the [project that hosts 'Superhero Cyborgs' (they don't call it that any more)](https://boostxbjr.org/)

## Plan 
- [ ] Go though the funder's book for Northern Ireland 
   -  [x] Go and get the book 
   - [x] [Shortlist charities](https://github.com/equalitytime/public/issues/89#issuecomment-549276176) 
   - [ ]  Send information to trustees: 
   - [ ]  Make sure Farset Laps and KateG have access to this issue. (And talk to Kate about costs-in-kind, you've miscommunicated there).  Raise the possibility of Farset taking on a larger role.
   - [ ] email the Funder to keep them in the loop
   - [ ] Make the calls to the set of 12 shortlisted funders. 
   - [ ] Create seperate issues for funders that are worth pursuing
- [ ] Go through funders central of for other NI charities. 
- [ ] Review the setup and see if we can cut costs anywhere.  
- [ ]  Find out if it would be possible to remove eQuality Time and our costs to reduce the amount.  
- [ ] Check Farset would be happy
- [ ] Check Funders would be happy
- [ ] Set a deadline to move over

**Comment by joereddington-public** [comment]
# Shortinglist in Charities to Approach for Funding. 
I went into Town on Daddy-Daughter day and went thought this: 
![Screenshot 2019-11-04 at 10 33 32](https://user-images.githubusercontent.com/40637406/68114730-a840c780-feee-11e9-9676-940ee098ba2a.png)

The page for Northern Ireland specifically was this (yes, there aren't many): 

![Screenshot 2019-11-04 at 09 09 16](https://user-images.githubusercontent.com/40637406/68109587-d7e9d280-fee2-11e9-9fdd-900ab9975db2.png)

The next job was to go through those charities and see if they would suit the Superhero Cyborg project. 

## The Big List 
* [Allen & Overy](http://www.allenovery.com/corporate-responsibility/charitable-giving/Pages/default.aspx) - they have a belfast office but seems to be only their legal service centre.  Seem quite big. Not giving new funds in 2019. 
* The Roger and Sarah Bancroft Clark Charitable Trust.  No website, based in Bath. Doesn't appear to have a connection to NI. 
* [Cash for kids](http://www.cashforkids.uk.com/locations/) in an umbrella organisaion, they have already picked their NI team. 
* [B&CE Charitable Trust](https://bandce.co.uk/corporate-responsibility/the-charitable-trust/help-for-education-and-training/) "Grants are available for projects that either promote careers in the construction industry or lead to accredited qualifications." We're *sort of* doing that.  No evidence of Northern Ireland based though...  best so far. Doesn't say what the grant sizes are: 0300 2000 600
* The church of Ireland Priorities fund is *for* Clergy. 
* Skipping the Animal Charity Trust (Should definately find ourselves) an animal project. 
* Enkalon Foundation looks pretty good actually.  Right sort of amount. NI, likes disability (a bit) closing date is the 13th November. Top answer so far. (also Farset labs is in the right bit of NI.  Really like this one. 
* [Iontaobhas na Gaelscolaíochta](http://www.iontaobhasnag.com/) is about Irish Language Education - I had a look from a WWW point of view, but nothing obvious. 
* [Halifax for Northern Ireland](https://www.halifaxfoundationni.org/welcome-grant-portal-halifax-foundation-northern-ireland) - In the right place. Might be good for £4k. Let us know in four months. 
* [P & C Hickinbotham](http://www.hickinbothamtrust.org.uk/index.html) does do NI, but only up to £1000
* [The Intergrated Education Fund](https://www.ief.org.uk/) is interested in supporting schools that have students from different religions. 
* [The ireland funds](https://irelandfunds.org/wp-content/uploads/2019/08/SMALL-GRANTS-ROUND-2019-APPLICATION-GUIDELINES-a.pdf) probabyl would have been quite good but we missed the window. 
* The kennedy Charitable Foundation](https://beta.charitycommission.gov.uk/charity-details/?regid=1052001&subid=0) is based in Altrincham and doesn't have that much money. 
* [The Allen Lane Foundation](https://allenlane.org.uk/applying-for-funding/) is probably good for Supertitle but not this. 
* [The leche Trust](http://www.lechetrust.org/) is based in London and focuses on performing arts and conservation 
* [Lord and Lady Lurgan Trust](http://lurgantrust.org/) - does like NI, up to 5k,  we are well passed the deadline though... http://lurgantrust.org/apply.html
* [TK Maxx and Homesense](https://beta.charitycommission.gov.uk/charity-details/?regid=1162073&subid=0) Seems to exist but that's all we need. I just did a social media post asking for more information. (I realise now I coudl have written it here)  - Also I can just ring the number on the charity commision webiste. 
* [Mazars Charitable Trust](https://beta.charitycommission.gov.uk/charity-details/?subid=0&regid=1150459) the contact details apear to be a gmail address and a mobile number... Worth giving them a ring...  
* [Esme michtelle](http://supportingcommunities.org/funding-news-1/2019/6/13/esme-mitchell-trust-grants-for-projects-of-a-heritage-cultural-or-artistic-nature) this is a good one, NI, likes a bit of design, considered monthly.  Love it. 
* [John Moores Foundation](http://www.jmf.org.uk/index.php/what-we-do-not-fund) looks good but they do have a problem with work done with Children in School time. 
* National Churches Trust is *for* churchs
* [The Community Foundation for Northern Ireland](https://communityfoundationni.org/achieving-impact/available-grants/) Lots of little ones, worth doing. 
* [Northern Phamacies Ltd Trust](https://www.charitycommissionni.org.uk/charity-details/?regid=101560&subid=0) they seem nice - they like heath, but mostly in a drugs way. Doesn't hurt to give them a call. 
* The Open House Trust is focused on developing countries and god. 
* The O'Sullivan Family Chariable Trust: 
![Screenshot 2019-11-04 at 10 24 52](https://user-images.githubusercontent.com/40637406/68114219-68c5ab80-feed-11e9-9ec7-87dbba357d04.png)
_That's a clear no_
* Skipping the 'Ouseley Church Music Trust' 
* [The Joseph Rank Trust](www.ranktrust.org/areas-of-interest.htm) is very christian. And quite angry about it. 
* The Royal British legion - I wouldn't have thought of it, but we *are* dealling with limb difference right?  Ah - No. It's Armed Service Personelle only. 
* [TACA](http://www.taca.ie/committee.asp) potentially good for WWW, but definately not for this. 
* [Ulster Garden Villiages ltd](http://ulstergardenvillages.co.uk/) this is a good one. Let's apply.  

## The smaller list of ones I thought we should approach.  
* [B&CE Charitable Trust](https://bandce.co.uk/corporate-responsibility/the-charitable-trust/help-for-education-and-training/) "Grants are available for projects that either promote careers in the construction industry or lead to accredited qualifications." We're *sort of* doing that.  No evidence of Northern Ireland based though...  best so far. Doesn't say what the grant sizes are: 0300 2000 600
* Enkalon Foundation looks pretty good actually.  Right sort of amount. NI, likes disability (a bit) closing date is the 13th November. Top answer so far. (also Farset labs is in the right bit of NI.  Really like this one. 
* [Halifax for Northern Ireland](https://www.halifaxfoundationni.org/welcome-grant-portal-halifax-foundation-northern-ireland) - In the right place. Might be good for £4k. Let us know in four months. 
* [The ireland funds](https://irelandfunds.org/wp-content/uploads/2019/08/SMALL-GRANTS-ROUND-2019-APPLICATION-GUIDELINES-a.pdf) probabyl would have been quite good but we missed the window. Maybe ring anyway? 
* [Lord and Lady Lurgan Trust](http://lurgantrust.org/) - does like NI, up to 5k,  we are well passed the deadline though... http://lurgantrust.org/apply.html
* [TK Maxx and Homesense](https://beta.charitycommission.gov.uk/charity-details/?regid=1162073&subid=0) Seems to exist but that's all we need. I just did a social media post asking for more information. (I realise now I coudl have written it here)  - Also I can just ring the number on the charity commision webiste. 
* [Mazars Charitable Trust](https://beta.charitycommission.gov.uk/charity-details/?subid=0&regid=1150459) the contact details apear to be a gmail address and a mobile number... Worth giving them a ring...  
* [Esme michtelle](http://supportingcommunities.org/funding-news-1/2019/6/13/esme-mitchell-trust-grants-for-projects-of-a-heritage-cultural-or-artistic-nature) this is a good one, NI, likes a bit of design, considered monthly.  Love it. 
* [John Moores Foundation](http://www.jmf.org.uk/index.php/what-we-do-not-fund) looks good but they do have a problem with work done with Children in School time. 
* [The Community Foundation for Northern Ireland](https://communityfoundationni.org/achieving-impact/available-grants/) Lots of little ones, worth doing. 
* [Northern Phamacies Ltd Trust](https://www.charitycommissionni.org.uk/charity-details/?regid=101560&subid=0) they seem nice - they like heath, but mostly in a drugs way. Doesn't hurt to give them a call. 

* [Ulster Garden Villiages ltd](http://ulstergardenvillages.co.uk/) this is a good one. Let's apply.  

## The list of funds that we should take to other projects. 
* [The Allen Lane Foundation](https://allenlane.org.uk/applying-for-funding/) is probably good for Supertitle but not this. 
* [TACA](http://www.taca.ie/committee.asp) potentially good for WWW, but definately not for this. 

# next actions 

- [ ]  Send this to trustees: 

> # Superhero Cyborgs, 
> [project link is here](https://github.com/equalitytime/public/issues/89) 
> As you know we're looking for Match funding for Superhero Cyborgs. I've been reviewing NI funders and, as you can see [here](https://github.com/equalitytime/public/issues/89) I've picked out 12 that are worth pursuing, of which I think four or five are actually really good.  Assuming that the trustees are fine with me approaching them I'll make some phone calls as an initial pitch.
 
- [x]  Make sure Farset Laps and KateG have access to this issue. 
- [x] email the Funder to keep them in the loop. 
- [ ] Make the calls to the set of 12 shortlisted funders.

**Comment by joereddington-public** [comment]
* [Allen & Overy](http://www.allenovery.com/corporate-responsibility/charitable-giving/Pages/default.aspx) - they have a belfast office but seems to be only their legal service centre.  Seem quite big. Not giving new funds in 2019. 
* The Roger and Sarah Bancroft Clark Charitable Trust.  No website, based in Bath. Doesn't appear to have a connection to NI. 
* [Cash for kids](http://www.cashforkids.uk.com/locations/) in an umbrella organisaion, they have already picked their NI team. 
* [B&CE Charitable Trust](https://bandce.co.uk/corporate-responsibility/the-charitable-trust/help-for-education-and-training/) "Grants are available for projects that either promote careers in the construction industry or lead to accredited qualifications." We're *sort of* doing that.  No evidence of Northern Ireland based though...  best so far. Doesn't say what the grant sizes are: 0300 2000 600
* The church of Ireland Priorities fund is *for* Clergy. 
* Skipping the Animal Charity Trust (Should definately find ourselves) an animal project. 
* Enkalon Foundation looks pretty good actually.  Right sort of amount. NI, likes disability (a bit) closing date is the 13th November. Top answer so far. (also Farset labs is in the right bit of NI.  Really like this one. 
* [Iontaobhas na Gaelscolaíochta](http://www.iontaobhasnag.com/) is about Irish Language Education - I had a look from a WWW point of view, but nothing obvious. 
*

**Comment by joereddington-public** [comment]
I've been making calls 
* Hello, I was hoping to speak to someone about your grant funding. Is this the right place? 

* I've got a project that I think broadly fits with your aims, but I want to have a quick chat first, would now be okay? 

* We're looking for match funding, we've got 50% of the project and we're looking for the rest.   

So, 

#### B&CE Charitable Trust 
I spoke to Claire, and I've drafted the following email to send to charitabletrust@bandce.co.uk

Hi Claire, 

We spoke on the phone a few minutes ago, I'm looking for match funding for a project running in NI. It's about Education, Training, and Construction, but we're a little unsure if it's *your* sort of Education, Training and Construction. 

It's a £20k project and we've found £10k for it.  I've attached the briefing note for the last funder, would it be possible for you to have a quick look to see if it matches up with your aims? 


#### Enkalon Foundation  
Seems suitable but Closes today! I need permission from trustees before I apply.  

The application is long but the main bits are :Project Outline (300 words) and Project Aims and Objectives (300 words) 

Relevent bits of the grant application policy:  
* At least one Trustee and the COO must review the full application and budget before submission and give positive yeses
* All Trustees are given at least 72 hours to review draft bids before that are submitted

#### LurganTrust
Grants are around £2,000, and wouldn't get the money before August

#### Halifax
Can't apply until January. 

#### The Ireland Funds
Won't open until mid-next year. 

#### TK Maxx and Homesense Foundation 
Switchboard says I should email Communityfund@tjxenurope.com

**Comment by joereddington** [comment]
I'm telling trustees I'd like to apply for Esme, John Moore and Uster garden villiages
