### ISSUE TITLE
Read the Green and Magenta Books

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#9]
For a long time we've been struggling to get our heads around funding application forms. We've been fairly sucessful, but most of that is on the 'unusual' application forms - ones that involve vidoes and in person interviews and so on.  

Part of this is that it's unclear to me how the people who write grant applictions think - and that makes it hard to show them the information they want in the order they want it. 

I recently asked a social policy academic about this and she recommended the Green and Magenta books, which are the government standard books for evaluating projects - I need to read them and share the notes with the rest of eQuality Time.  

# Resources 
* [The Green Book with Joe's highlights](https://www.dropbox.com/s/ra7w1zyc42arc58/The_Green_Book.pdf?dl=0)

**Comment by joereddington-public** [comment]
started reading 16:31.

**Comment by joereddington-public** [comment]
Some notes: 

We should look at papers that cite the green book, that apply it to education.  It would be nice to be able to put a cost-benefit analysis forward...

We should also look up the insurance rates for Open Voice Factory...

I want to know if anyone has done this for AAC devices... 

<img width="765" alt="screen shot 2018-06-27 at 16 48 57" src="https://user-images.githubusercontent.com/40637406/41985016-0d9fcc84-7a2a-11e8-8d59-6a20f4f8fc16.png">

**Comment by joereddington-public** [comment]
Got as far as p62 - which is the start of the Annexes.  Good to go from here... 
[The_Green_Book.pdf](https://github.com/eQualityTime/Public/files/2142005/The_Green_Book.pdf)

**Comment by joereddington** [comment]
Closing this. We have other approaches to fundrasing right now.
