### ISSUE TITLE
Submit Bid to the Arts Council

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/Public#94]
# Summary 
* We've applied to the Arts Council ten times to run a professional team writing sprint
* Each time we get a rejection Joe carefully goes through the feedback and addresses all parts 
* Looking a scores over the years we have basically been getting the same ones over and over again. 
* We need to start this from scratch because incremental improvement is very much not working for us. 

# Working folder
The documents for our most recent bid are: 
* [The working folder](https://drive.google.com/drive/folders/1MMBkJvV3K999OU90VneIG5y9Sem8ceia) 

# Resources 
* [2021 how to apply guidance over £15k)](https://www.artscouncil.org.uk/sites/default/files/download-file/ACNLPG_Over_%C2%A315K_16032021_0.pdf)
* [Audience Developement Plan (with FAQ bit)](https://github.com/eQualityTime/Public/files/3271519/ECHO.Audience.Development.Plan.docx)
* [Budget and Gantt Chart](https://github.com/eQualityTime/Public/files/3271639/ECHO.-.TOOMANYCOOKS.budget.xlsx)
* [All the questions and answers](https://github.com/eQualityTime/Public/files/3271672/ECHO.arts.project.docx)
* [Some infromation on questions from arts council](https://www.artscouncil.org.uk/sites/default/files/download-file/ACNLPG_Over_%C2%A315K_July_2020_0.pdf) 
* [Most recent feedback as an excel file](https://github.com/eQualityTime/Public/files/3844795/Appraisal.xlsx)
* [List of questions to ask self](https://www.artscouncil.org.uk/sites/default/files/download-file/Unsuccessful_GFTA_applications_over_15000_Oct_2016.pdf)
* Various Previous Bids, e.g. #1 , #59 , #78 

# Background
We had our tenth rejection from the arts council recently. Ten is a round enough number that it's worth looking into  
We've applied to the arts council 10 times in total. These are our results

| Decision Date |                     | Quality                   | Public engagement | Management | Finance |
|------------|---------------------|---------------------------|-------------------|------------|---------|
| 28/6/2016  | TooManyCooks        | "Underdeveloped"          | n/a               |  n/a       |  n/a    |
| 11/11/2016 | TooManyCooks 2      | "Underdeveloped"          | n/a               | n/a        | n/a     |
| 10/10/2017 | ANGEL               | Met                       | Met               | Met        | Met     |
| 30/3/2017  | Shock and Awe       | Potential                 | Met               | Met        | Met     |
| 21/6/2017  | Awe and Shock       | "too similar to last one" | n/a               | n/a        | n/a     |
| 14/3/2018  | Battlecry           |  "unbalanced budget"      | n/a               | n/a        | n/a     |
| 8/5/2018   | Codex TooManyCooks  | "unbalanced budget"       | n/a               | n/a        | n/a     |
| 18/7/2018  | Codex TooManyCooks  | Met                       | Met               | Potential  | Not met |
| 30/4/2019  | Discord             | Met                       | Met               | Strong     | Met     |
| 15/10/2019 | Echo                | Met                       | Met               | Met        | Met     |

For the ones that got through to the appraisal stage, shown below, it's clear that we've gone down in the scores exactly as much as we've gone up, despite following all feedback.  (Or, in the case of the time we've gone from 'Strong' to 'met', literally copying and pasting the last one) 

(The potential scores are Outstanding, Strong, Met, Potential, or Not met). 

| Decision Date |                     | Quality                   | Public engagement | Management | Finance |
|------------|---------------------|---------------------------|-------------------|------------|---------|
| 10/10/2017 | ANGEL               | Met                       | Met               | Met        | Met     |
| 30/3/2017  | Shock and Awe       | Potential                 | Met               | Met        | Met     |
| 18/7/2018  | Codex TooManyCooks  | Met                       | Met               | Potential  | Not met |
| 30/4/2019  | Discord             | Met                       | Met               | Strong     | Met     |
| 15/10/2019 | Echo                | Met                       | Met               | Met        | Met     |

This is deeply frustrating. 

So, perhaps we need an entirely new approach, and the bid needs to be written deeply differently.  

What options do we have? 

* Contacting people we know that have had a successful bid 
* Paying for a former arts council person to review 
* Brainstorming a list of new ways to approach the bid  
  * Drop the collaborative angle 
  * Add some new people to the bid, possibly on a panel  
  * Drop everything that isn't the central idea: books written by teams are better. 
  * Drop the bit were we provide any of the money.
* Having the writers all ready to go as a list. 
* Read application again looking at https://www.artscouncil.org.uk/sites/default/files/download-file/Unsuccessful_GFTA_applications_over_15000_Oct_2016.pdf 
* Rewrite the application from scratch using only the bits of the application that had good feedback before (or, just using their words) 

Let's take this view: 

* You can't improve incrementally from 'Met' to 'Outstanding', and indeed, we haven't. 
* If we rewrite significantly, we'll get much better information about what works and doesn't work: i.e, we might not get the bid this time, but we improve out chances *next* time. 

# Plan 
- [x] Choose a new name 
	* FERRUM: the plan...  
- [x] Ask some people if they would like to be in on the bid.
        * We got a great review from someone we know
- [x] Create online versions of the documents
## After Lockdown 
- [x] Review the how to apply guidence 
- [x] Review the current application form 
- [x] Complete the audience developement plan 
  * Go through the four documents above and find out any nice phrases that we can use, and reference 
  * Add a bunch of images and quotes from our previous writers/teachers  
  * Talk about Google Ad Grants. 
- [x] Complete the management section
  * Write the evaluation 
  * Write the management of stages
  
- [x] Complete the public engagement section
- [x] Complete the finance section. 
- [x] Write a detailed description in each of the budget lines 
  - [x] Including why buying is better than renting and detailed of three quotes.  

- [x] Write new versions of the answers 
         - [x]  [Enter Arts Council Site to check to see if anything has changed](https://github.com/eQualityTime/Public/issues/94#issuecomment-667924955) 
- [ ] Add a cashflow document.
- [x] Send to trustee for review 
- [x] Put everything through Simplewriter and TTS 
- [x] Submit

**Comment by joereddington-public** [comment]
[FERROS.-.TOOMANYCOOKS.budget.xlsx](https://github.com/eQualityTime/Public/files/3844832/FERROS.-.TOOMANYCOOKS.budget.xlsx)
[FERROS.arts.project.docx](https://github.com/eQualityTime/Public/files/3844875/FERROS.arts.project.docx)
[FERROS.Audience.Development.Plan.docx](https://github.com/eQualityTime/Public/files/3844876/FERROS.Audience.Development.Plan.docx)

**Comment by joereddington** [comment]
Here's the plan. 
- [ ] Switch the links to dropbox versions (download, upload, copy link) 
- [ ] Lookup Roy's Notes 
- [ ] Put into Simplewriter/hemmingway and move forward.

**Comment by joereddington** [comment]
## 03/08/20 09:05 to 10:44, Working on Arts Grant.  
 * Amazed to find the last submission was almost exactly a year ago 
 * Filling out arts council file  
 * New question alert! "Our 10-year strategy, Let’s Create, has three Outcomes. Tell us which of our Outcomes, listed below, you think your project will contribute to.
* The questions are suitably different that I would like to start again, if only as an exercise.
* Created the files on Google Drive.

**Comment by joereddington** [comment]
## 04/08/20 06:17 to 07:50, Working on https://github.com/eQualityTime/Public/issues/94
I wrote one new answer completly and started another, then I found a question that needed answering at https://twitter.com/joereddington/status/1290555061240762368.  I wrote this email: 

-----------

Hi team! 

My name is Joseph Reddington, my username on grantium is joereddington. 

I'm filling out the application form for you main grants and I've reached this page: 

![Screenshot 2020-08-04 at 08 45 32](https://user-images.githubusercontent.com/4369547/89273932-237b0980-d638-11ea-885c-4bc69f78f3e5.png)

 
There are two boxes that have character counts but no questions.  Also, the guidance here: (https://www.artscouncil.org.uk/sites/default/files/download-file/ACNLPG_Over_%C2%A315K_July_2020_0.pdf) shows a question "How will this project have a wider impact? (up to 1500 characters)" which doesn't appear to have a box on the form.  

![Screenshot 2020-08-04 at 08 43 44](https://user-images.githubusercontent.com/4369547/89273969-2d9d0800-d638-11ea-9969-515e045ef238.png)


I'm quite confused. Can you tell me: 

- What I put in the two boxes that don't have questions? 
- Where I put the answer to the wider impact question? Thank you for your help. 

Joe

------


The answer turns out to be this: 

![Screenshot 2021-07-28 at 10 50 48](https://user-images.githubusercontent.com/4369547/127302392-e503df8e-74e7-4297-80d2-e454fa104c3f.png)

----

* Rewritten the issue heavily.
* What's the next action? 
   * Rewrite the second question.
   * Look at the guide document 
      * Review the supplemental documentation: https://www.artscouncil.org.uk/sites/default/files/download-file/ACNLPG_supplementary_note_31July_2020_0.pdf 
         * "We have removed the requirement for a minimum 10 per cent match funding during this period"  
      * Looking at the info sheets at:
         * Including the audience developement plan: https://www.artscouncil.org.uk/sites/default/files/download-file/Information_sheets_Audience_development_marketing_Project_grants_170518.pdf 
        * Including research and devleopement (which this project very much is) https://www.artscouncil.org.uk/sites/default/files/download-file/Information_sheets_Research_development_Project_grants.pdf 
   * Put yesterdays stream onto the github issue

**Comment by joereddington** [comment]
## 28/07/21 09:27 to 12:25,  Opening this back up. 
Opening this project back up.  That means a full review of the documentation in case things have changed. 

* We start by taking a quiz https://www.artscouncil.org.uk/national-lottery-project-grants/applying-national-lottery-project-grants-three-steps 
* I've filled in the eligibility questionnaire and passed. We are bidding for  £ 27,333.13  
* I've gone right through the appilcaiton form and pulled out the question. 
* Next action is to work though the guidance on questions, make the list of points to hit, write them, and thne go back through the list at the start of the section. 


* Haven't got a place for if the target audiences for the activity are clearly identified 


From the main site: 

> We've reopened the fund with additional supplementary guidance which applies until 31 August 2021 to help fund independent organisations, creative practitioners and freelancers as quickly as possible. We also have a ring-fenced budget of £1.5 million until 31 March 2022 available within National Lottery Project Grants specifically to support the grassroots music sector. 


From the [covid guidance which applies until August 31st]( https://www.artscouncil.org.uk/sites/default/files/download-file/ACPG_supplementary_guidance_02032021_0.pdf).


      All potential applicants should read both this note and the How to Apply guidance before applying.


> If you’re undertaking organisational development or focusing on research and development, you might use this section to tell us how the work you’re proposing will mean you are better able to engage people with your work in the future. We understand that good public engagement will look different – it’s important that we find out about all the different ways the work we support through Project Grants in this period will reach people. 

> However, if your only option is to use your organisation’s own reserves as match funding in a way that could put your organisation in a difficult financial position, we would advise not including match funding.

**Comment by joereddington** [comment]
# 02/08/21 08:03 to 08:52, +EQT Live on arts council. 
* Working on the management section
  * Wrote the 'work already done' section - but it was a rewrite rather than a start-from-scratch
  * Worked out that I need to do the Audience development plan before the Evalutation because those are the SMART goals that the Evaluation is testing
  * Last time the evaluation feedback was: 

  "There is some indication that performance and achievements during the activity will be monitored during the project, however, further indication of how quantitative data as well as qualitative data will be collated would have strengthened the application. An updated evaluation plan should be included as an initial payment condition."  

  * I've checked and they are willing to read the ADP as part of the Management section
    * Looking at the ADP feedback from last time - it's clear that I should probably start entirely again with that section. 


* Moved on to work on the ADP 
  * ADP notes: https://www.artscouncil.org.uk/sites/default/files/download-file/Information_sheets_Audience_development_marketing_Project_grants_170518.pdf
  * Other ADPs" 
    * https://www.elanvalley.org.uk/sites/default/files/assets/LCAP3_Audience%20Development%20Plan.pdf?language=en 
    * https://www.elanvalley.org.uk/sites/default/files/assets/LCAP3_Audience%20Development%20Plan.pdf?language=en 
    * https://rosiekay.co.uk/wp-content/uploads/2016/10/Marketing-Audience-Development-plan.pdf 
    * https://democracy.bristol.gov.uk/documents/s18395/A1ii%20-%20Audience%20Development%20Plan%202018-2022.pdf 

## 02/08/21 09:46 to 11:29, Back on Arts Council +EQT
* Rewriting this to get my head back in the game
* Literally 20 things to do. I really want to get this "Done Done" but I also want it off my desk today.  
* Rewrite audience development plan 
  * Moved over the notes on the public engagement questions 
  * I have put the expected headings from the arts council into the ADP. 
  * Now to Move 'demand for our work' to each audience section and 'give details of any research carried out' 
  * I've added (linked) budget and timeline to the ADP 
  * Working through the rewrite, have done the SMART goals. 

* Time to go and make lunch JUST  I as I was getting into a rythm. Will come back later
 

## 02/08/21 13:03 to 13:45,  Arts Council +EQT
Wow - my lunch breaks are massive. 
* Oh man, we've got an evaluaiton in here as well don't we! Sigh. 
  * I think I'm going to end up replicating the one for the other side. 

Okay, time for images. 

## 02/08/21 14:56 to 15:23, arts  again +EQT  
We know the organisation has developed if: 
* We have increased our profile in the media 
* We have improved the system for writing books 
  * Our survay choose our book in a blind test. 

We know the artists have developed 
* They have produced work, been paid, got a book, look forward to royalties.

**Comment by joereddington** [comment]
## 04/09/21 11:15 to 13:00, Working on https://github.com/eQualityTime/Public/issues/94  +EQT
* The github issue doesn't clearly outline the next steps. And it should. o
* Review
  * Quality Section is fine. 
  * Public engagement isn't written at all. 
  * The start of the budget is great, it ends not brilliantly. 
  * Management isn't done.

**Comment by joereddington** [comment]
Submitted and done yesterday.
